### PR TITLE
disable path if no composer available, fixes #4101

### LINKED ISSUE #4101: "composer show --path --platform" throws an exception
I was genuinely curious if Composer knew where my platform packages are. :stuck_out_tongue: 
Below the story:
```
$ php --version
PHP 5.5.23 (cli) (built: Mar 23 2015 01:47:37)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

$ composer --version
Composer version 1.0-dev (65dd1f7137abf80b08a1dac29379bf266a425474) 2015-06-02 13:47:52

$ composer show --path --platform
composer-plugin-apiPHP Fatal error:  Call to a member function getInstallationManager() on a non-object in phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/src/Composer/Command/ShowCommand.php on line 220
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar:0
PHP   2. require() /usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar:25
PHP   3. Composer\Console\Application->run() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/bin/composer:43
PHP   4. Symfony\Component\Console\Application->run() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/src/Composer/Console/Application.php:82
PHP   5. Composer\Console\Application->doRun() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/src/Composer/Console/Application.php:146
PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   8. Symfony\Component\Console\Command\Command->run() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   9. Composer\Command\ShowCommand->execute() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257

Fatal error: Call to a member function getInstallationManager() on a non-object in phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/src/Composer/Command/ShowCommand.php on line 220

Call Stack:
    0.0041     408648   1. {main}() /usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar:0
    0.0044     410424   2. require('phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/bin/composer') /usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar:25
    0.0315    3496176   3. Composer\Console\Application->run() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/bin/composer:43
    0.0339    3811992   4. Symfony\Component\Console\Application->run() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/src/Composer/Console/Application.php:82
    0.0348    3936992   5. Composer\Console\Application->doRun() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
    0.0358    4042312   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/src/Composer/Console/Application.php:146
    0.0358    4042752   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
    0.0359    4043224   8. Symfony\Component\Console\Command\Command->run() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
    0.0362    4049912   9. Composer\Command\ShowCommand->execute() phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
```
Not sure what fix should be applied here. `\Composer\Command\ShowCommand::execute()` is just too scary.

### PR DESCRIPTION
**Pull request by alcohol**
gracefully remove the option and continue, after informing the user

### CODE REVIEW

File: src/Composer/Command/ShowCommand.php [hunk 1]
```diff
@@ -196,6 +196,11 @@ protected function execute(InputInterface $input, OutputInterface $output)
                     $width--;
                 }
 
+                if ($input->getOption('path') && null === $composer) {
+                    $this->getIO()->writeError('No composer.json found in the current directory, disabling "path" option');
```
Comment (nevvermind) [inline src/Composer/Command/ShowCommand.php]: Shouldn't this be on a debug verbosity?

Comment (nevvermind) [inline src/Composer/Command/ShowCommand.php]: The message should state: `composer.json was not found in the current directory. Disabling "path" option.`. It has a more humane sound to it.

Comment (alcohol) [inline src/Composer/Command/ShowCommand.php]: I kept the message in line with other messages in the show command.

Comment (nevvermind) [inline src/Composer/Command/ShowCommand.php]: Sure, ok. But you're adding to the "grunt work" (I'm quoting you) in case a log verbosity overhaul is needed in the future.

Comment (alcohol) [inline src/Composer/Command/ShowCommand.php]: True, but until any decisions are made on how/what regarding that, it doesn't make sense to "plan for the future" as long as the future remains unclear.
