### PR TITLE
Fix validate strict warnings

### LINKED ISSUE #8602: `validate` command: with `--no-check-publish`, adding `--strict` makes warnings disappear from output
My `composer.json`:

```json
{
    "type": "project",
    "license": "proprietary"
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.3
PHP version: 7.2.25
PHP binary path: /usr/local/bin/php
```

When I run this command:

```
composer validate --no-check-publish --strict ; echo $?
```

I get the following output:

```
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
0
```

And I expected this to happen:

to get same output as the command without the `--strict` option, i.e.:

```
./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
name : The property name is required
description : The property description is required
0
```

Noticed in https://github.com/ergebnis/composer-normalize/issues/349

Refs #7637
See also #7207

### PR DESCRIPTION
**Pull request by guilliamxavier**
- The first commit fixes a regression in #7637
- The second commit fixes #8602
- Extra commits are to improve maintainability

### CODE REVIEW

File: src/Composer/Command/ValidateCommand.php [hunk 1]
```diff
@@ -125,42 +127,51 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
+        }
+
+        if ($doPrintSchemaUrl) {
+            $io->writeError('<warning>See https://getcomposer.org/doc/04-schema.md for details on the schema</warning>');
         }
 
+        $allWarnings = $warnings;
+
         // If checking publish errors, display them as errors, otherwise just show them as warnings
         // Skip when it is a strict check and we don't want to check publish errors
```
Comment (Seldaek) [inline src/Composer/Command/ValidateCommand.php]: This line and the one below at 161 are not relevant anymore I think? Or at least not at the right spot.

File: src/Composer/Command/ValidateCommand.php [hunk 2]
```diff
@@ -125,42 +127,51 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
         if ($checkLock) {
             $errors = array_merge($errors, $lockErrors);
-        } elseif (!$isStrict) {
-            $warnings = array_merge($warnings, $lockErrors);
+        } else {
+            $allWarnings = array_merge($allWarnings, $lockErrors);
+        }
+
+        if (!$isStrict) {
+            $warnings = $allWarnings;
```
Comment (Seldaek) [inline src/Composer/Command/ValidateCommand.php]: Would be good to add a comment here instead.. As far as I understand it is to avoid setting the exit code to 1 in case --strict and --no-check-publish/--no-check-lock are combined?

File: src/Composer/Command/ValidateCommand.php [hunk 3]
```diff
@@ -123,44 +125,48 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
+            $io->write('<info>' . $name . ' is valid</info>');
+            // if ($lockErrors) then they will be displayed below
+        }
+
+        if ($doPrintSchemaUrl) {
+            $io->writeError('<warning>See https://getcomposer.org/doc/04-schema.md for details on the schema</warning>');
         }
 
+        // Avoid setting the exit code to 1 in case --strict and --no-check-publish/--no-check-lock are combined
+        $allWarnings = $warnings;
```
Comment (guilliamxavier) [inline src/Composer/Command/ValidateCommand.php]:
```suggestion
        $extraWarnings = [];
```

File: src/Composer/Command/ValidateCommand.php [hunk 4]
```diff
@@ -123,44 +125,48 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
+
         // If checking publish errors, display them as errors, otherwise just show them as warnings
-        // Skip when it is a strict check and we don't want to check publish errors
         if ($checkPublish) {
             $errors = array_merge($errors, $publishErrors);
-        } elseif (!$isStrict) {
-            $warnings = array_merge($warnings, $publishErrors);
+        } else {
+            $allWarnings = array_merge($allWarnings, $publishErrors);
```
Comment (guilliamxavier) [inline src/Composer/Command/ValidateCommand.php]:
```suggestion
            $extraWarnings = array_merge($extraWarnings, $publishErrors);
```

File: src/Composer/Command/ValidateCommand.php [hunk 5]
```diff
@@ -123,44 +125,48 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
         }
 
         // If checking lock errors, display them as errors, otherwise just show them as warnings
-        // Skip when it is a strict check and we don't want to check lock errors
         if ($checkLock) {
             $errors = array_merge($errors, $lockErrors);
-        } elseif (!$isStrict) {
-            $warnings = array_merge($warnings, $lockErrors);
+        } else {
+            $allWarnings = array_merge($allWarnings, $lockErrors);
```
Comment (guilliamxavier) [inline src/Composer/Command/ValidateCommand.php]:
```suggestion
            $extraWarnings = array_merge($extraWarnings, $lockErrors);
```

File: src/Composer/Command/ValidateCommand.php [hunk 6]
```diff
@@ -123,44 +125,48 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
         }
 
         $messages = array(
             'error' => $errors,
-            'warning' => $warnings,
+            'warning' => $allWarnings,
```
Comment (guilliamxavier) [inline src/Composer/Command/ValidateCommand.php]:
```suggestion
            'warning' => array_merge($warnings, $extraWarnings),
```

**Comment by Seldaek** [comment]
Yup thanks that is easier to follow I think

**Comment by guilliamxavier** [comment]
Oops I had forgotten PHP 5.3, sorry, fixed

**Comment by Seldaek** [comment]
Thanks
