### PR TITLE
Ensure stat cache is cleared for junctions

### LINKED ISSUE #5053: Junction content still gets deleted after composer update
This is similar to #4955, but happens only on consecutive updates, **if** the dependency composer.json has been updated. All the junction content is gone after this:

```
Updating dependencies (including require-dev)
  - Removing test/a (dev-master)

  [RuntimeException]
  Package test/a cannot install to "... src\Test\A" inside its source at "... src\Test\A"

Exception trace:
 () at phar://composer.phar/src/Composer/Downloader/PathDownloader.php:45
 Composer\Downloader\PathDownloader->download() at phar://composer.phar/src/Composer/Downloader/DownloadManager.php:213
 Composer\Downloader\DownloadManager->download() at phar://composer.phar/src/Composer/Downloader/DownloadManager.php:260
 Composer\Downloader\DownloadManager->update() at phar://composer.phar/src/Composer/Installer/LibraryInstaller.php:198
 Composer\Installer\LibraryInstaller->updateCode() at phar://composer.phar/src/Composer/Installer/LibraryInstaller.php:110
 Composer\Installer\LibraryInstaller->update() at phar://composer.phar/src/Composer/Installer/InstallationManager.php:172
 Composer\Installer\InstallationManager->update() at phar://composer.phar/src/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at phar://composer.phar/src/Composer/Installer.php:592
 Composer\Installer->doInstall() at phar://composer.phar/src/Composer/Installer.php:219
 Composer\Installer->run() at phar://composer.phar/src/Composer/Command/UpdateCommand.php:173
 Composer\Command\UpdateCommand->execute() at phar://composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar://composer.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar://composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar://composer.phar/src/Composer/Console/Application.php:166
 Composer\Console\Application->doRun() at phar://composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar://composer.phar/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar://composer.phar/bin/composer:43
 require() at composer.phar:24
```

Junction lstat is as follows:
```php
Array
(
    [0] => 4
    [1] => 0
    [2] => 0
    [3] => 1
    [4] => 0
    [5] => 0
    [6] => 4
    [7] => 0
    [8] => 1457828772
    [9] => 1457828772
    [10] => 1457828772
    [11] => -1
    [12] => -1
    [dev] => 4
    [ino] => 0
    [mode] => 0
    [nlink] => 1
    [uid] => 0
    [gid] => 0
    [rdev] => 4
    [size] => 0
    [atime] => 1457828772
    [mtime] => 1457828772
    [ctime] => 1457828772
    [blksize] => -1
    [blocks] => -1
)
```

And this is the premise: (On Windows 10)

```json
# composer.json
{
    "repositories": [
        {"type": "path", "url": "src/Test/*"}
    ],

    "require": {
        "test/a": "@dev"
    }
}

# src/Test/A/composer.json
{
    "name": "test/a",
    "description": "test"
}
```

1. Run `composer update`
2. Modify description in src/Test/A/composer.json
3. Run `composer update`
4. src/Test/A is empty, while the junction vendor/test/a remains

### PR DESCRIPTION
**Pull request by curry684**
In certain complex situations where the same folder is created and removed during the same run intermediate data may be cached misrepresenting a junction as an actual folder.

Should fix #5053

### CODE REVIEW

File: src/Composer/Util/Filesystem.php [hunk 1]
```diff
@@ -637,7 +638,10 @@ public function isJunction($junction)
          *
          * #define	_S_IFDIR	0x4000
          * #define	_S_IFREG	0x8000
+         *
+         * Stat cache should be cleared before to avoid accidentally reading wrong information from previous installs.
          */
+        clearstatcache(true, $junction);
```
Comment (staabm) [inline src/Composer/Util/Filesystem.php]: is it really required on each "read" or would it be enough to clear the cache on all "write" junction related operations?

Comment (curry684) [inline src/Composer/Util/Filesystem.php]: It's not *required* but I added this one for safety due to the possibly catastrophic consequences. This is an extra safeguard to an outside force changing the folder in between, for example in future situations where we fork parallel installers.
