### PR TITLE
Suppress error when chdir($oldWorkingDir); unsuccessful

### LINKED ISSUE #9649: chdir(): Permission denied (errno 13)
When running composer update from CLI (via Plesk's composer install) via this command:

    sudo -u ben /opt/plesk/php/7.3/bin/php /usr/lib64/plesk-9.0/composer.phar update -d /var/www/vhosts/ben.test.system/httpdocs -vvv

...I get the following exception:

    ...
    Installing dependencies from lock file (including require-dev)
    Nothing to install, update or remove
    Generating autoload files
    5 packages you are using are looking for funding.
    Use the `composer fund` command to find out more!

      [ErrorException]
      chdir(): Permission denied (errno 13)

    Exception trace:
     () at phar:///usr/lib64/plesk-9.0/composer.phar/src/Composer/Console/Application.php:313
     Composer\Util\ErrorHandler::handle() at n/a:n/a
     chdir() at phar:///usr/lib64/plesk-9.0/composer.phar/src/Composer/Console/Application.php:313
     Composer\Console\Application->doRun() at phar:///usr/lib64/plesk-9.0/composer.phar/vendor/symfony/console/Application.php:117
     Symfony\Component\Console\Application->run() at phar:///usr/lib64/plesk-9.0/composer.phar/src/Composer/Console/Application.php:122
     Composer\Console\Application->run() at phar:///usr/lib64/plesk-9.0/composer.phar/bin/composer:63
     require() at /usr/lib64/plesk-9.0/composer.phar:24

I installed composer from source in order to find out what working directory it was trying to change to and it was, in fact, the home directory of the admin user account I was running the CLI script from, which I suppose makes sense as the user `ben` can't see into that directory.

However as everything else worked as expected and this error happens almost literally right at the end of the program, I wonder if this particular error should be downgraded to a warning?
It would also be useful if it mentioned which directory it was trying to chdir() to.

I'll create a PR if I get time, but I thought it was worth mentioning as I found nothing when Googling and it's taken me quite a while to get to this point!

### PR DESCRIPTION
**Pull request by bbeckford**
resolves #9649

### CODE REVIEW

File: src/Composer/Console/Application.php [hunk 1]
```diff
@@ -309,8 +309,11 @@ function_exists('php_uname') ? php_uname('s') . ' / ' . php_uname('r') : 'Unknow
 
             $result = parent::doRun($input, $output);
 
+            // chdir back to $oldWorkingDir if set
             if (isset($oldWorkingDir)) {
-                chdir($oldWorkingDir);
+                Silencer::call(function () use ($oldWorkingDir) {
+                    chdir($oldWorkingDir);
+                });
```
Comment (Seldaek) [inline src/Composer/Console/Application.php:316]: This is enough :) 

```suggestion
                Silencer::call('chdir', $oldWorkingDir);
```

Comment (bbeckford) [reply src/Composer/Console/Application.php]: Of course!

**Comment by Seldaek** [comment]
Thanks :)
