### PR TITLE
Fix JSON manipulation issue with large files and jit enabled

### LINKED ISSUE #9595: composer config platform-check false + big composer.json => PREG_JIT_STACKLIMIT_ERROR
My `composer.json`:

```json
{
    "name": "leoloso/pop",
    "require": {
        "php": "^7.4|^8.0",
        "ext-mbstring": "*",
        "brain/cortex": "~1.0.0",
        "composer/installers": "~1.0",
        "composer/semver": "^1.5",
        "erusev/parsedown": "^1.7",
        "guzzlehttp/guzzle": "~6.3",
        "jrfnl/php-cast-to-type": "^2.0",
        "league/pipeline": "^1.0",
        "lkwdwrd/wp-muplugin-loader": "dev-feature-composer-v2",
        "obsidian/polyfill-hrtime": "^0.1",
        "psr/cache": "^1.0",
        "symfony/cache": "^5.1",
        "symfony/config": "^5.1",
        "symfony/dependency-injection": "^5.1",
        "symfony/dotenv": "^5.1",
        "symfony/expression-language": "^5.1",
        "symfony/polyfill-php72": "^1.18",
        "symfony/polyfill-php73": "^1.18",
        "symfony/polyfill-php74": "^1.18",
        "symfony/polyfill-php80": "^1.18",
        "symfony/property-access": "^5.1",
        "symfony/yaml": "^5.1"
    },
    "require-dev": {
        "johnpbloch/wordpress": ">=5.5",
        "phpstan/phpstan": "^0.12",
        "phpunit/phpunit": ">=9.3",
        "rector/rector": "^0.9",
        "squizlabs/php_codesniffer": "^3.0",
        "symfony/var-dumper": "^5.1",
        "symplify/monorepo-builder": "^9.0",
        "szepeviktor/phpstan-wordpress": "^0.6.2"
    },
    "autoload": {
        "psr-4": {
            "GraphQLAPI\\ConvertCaseDirectives\\": "layers/GraphQLAPIForWP/plugins/convert-case-directives/src",
            "GraphQLAPI\\GraphQLAPI\\": "layers/GraphQLAPIForWP/plugins/graphql-api-for-wp/src",
            "GraphQLAPI\\SchemaFeedback\\": "layers/GraphQLAPIForWP/plugins/schema-feedback/src",
            "GraphQLByPoP\\GraphQLClientsForWP\\": "layers/GraphQLByPoP/packages/graphql-clients-for-wp/src",
            "GraphQLByPoP\\GraphQLEndpointForWP\\": "layers/GraphQLByPoP/packages/graphql-endpoint-for-wp/src",
            "GraphQLByPoP\\GraphQLParser\\": "layers/GraphQLByPoP/packages/graphql-parser/src",
            "GraphQLByPoP\\GraphQLQuery\\": "layers/GraphQLByPoP/packages/graphql-query/src",
            "GraphQLByPoP\\GraphQLRequest\\": "layers/GraphQLByPoP/packages/graphql-request/src",
            "GraphQLByPoP\\GraphQLServer\\": "layers/GraphQLByPoP/packages/graphql-server/src",
            "Leoloso\\ExamplesForPoP\\": "layers/Misc/packages/examples-for-pop/src",
            "PoPSchema\\BasicDirectives\\": "layers/Schema/packages/basic-directives/src",
            "PoPSchema\\BlockMetadataWP\\": "layers/Schema/packages/block-metadata-for-wp/src",
            "PoPSchema\\CDNDirective\\": "layers/Schema/packages/cdn-directive/src",
            "PoPSchema\\CategoriesWP\\": "layers/Schema/packages/categories-wp/src",
            "PoPSchema\\Categories\\": "layers/Schema/packages/categories/src",
            "PoPSchema\\CommentMetaWP\\": "layers/Schema/packages/commentmeta-wp/src",
            "PoPSchema\\CommentMeta\\": "layers/Schema/packages/commentmeta/src",
            "PoPSchema\\CommentMutationsWP\\": "layers/Schema/packages/comment-mutations-wp/src",
            "PoPSchema\\CommentMutations\\": "layers/Schema/packages/comment-mutations/src",
            "PoPSchema\\CommentsWP\\": "layers/Schema/packages/comments-wp/src",
            "PoPSchema\\Comments\\": "layers/Schema/packages/comments/src",
            "PoPSchema\\ConvertCaseDirectives\\": "layers/Schema/packages/convert-case-directives/src",
            "PoPSchema\\CustomPostMediaMutationsWP\\": "layers/Schema/packages/custompostmedia-mutations-wp/src",
            "PoPSchema\\CustomPostMediaMutations\\": "layers/Schema/packages/custompostmedia-mutations/src",
            "PoPSchema\\CustomPostMediaWP\\": "layers/Schema/packages/custompostmedia-wp/src",
            "PoPSchema\\CustomPostMedia\\": "layers/Schema/packages/custompostmedia/src",
            "PoPSchema\\CustomPostMetaWP\\": "layers/Schema/packages/custompostmeta-wp/src",
            "PoPSchema\\CustomPostMeta\\": "layers/Schema/packages/custompostmeta/src",
            "PoPSchema\\CustomPostMutationsWP\\": "layers/Schema/packages/custompost-mutations-wp/src",
            "PoPSchema\\CustomPostMutations\\": "layers/Schema/packages/custompost-mutations/src",
            "PoPSchema\\CustomPostsWP\\": "layers/Schema/packages/customposts-wp/src",
            "PoPSchema\\CustomPosts\\": "layers/Schema/packages/customposts/src",
            "PoPSchema\\EventMutationsWPEM\\": "layers/Schema/packages/event-mutations-wp-em/src",
            "PoPSchema\\EventMutations\\": "layers/Schema/packages/event-mutations/src",
            "PoPSchema\\EventsWPEM\\": "layers/Schema/packages/events-wp-em/src",
            "PoPSchema\\Events\\": "layers/Schema/packages/events/src",
            "PoPSchema\\EverythingElseWP\\": "layers/Schema/packages/everythingelse-wp/src",
            "PoPSchema\\EverythingElse\\": "layers/Schema/packages/everythingelse/src",
            "PoPSchema\\GenericCustomPosts\\": "layers/Schema/packages/generic-customposts/src",
            "PoPSchema\\GoogleTranslateDirectiveForCustomPosts\\": "layers/Schema/packages/google-translate-directive-for-customposts/src",
            "PoPSchema\\GoogleTranslateDirective\\": "layers/Schema/packages/google-translate-directive/src",
            "PoPSchema\\HighlightsWP\\": "layers/Schema/packages/highlights-wp/src",
            "PoPSchema\\Highlights\\": "layers/Schema/packages/highlights/src",
            "PoPSchema\\LocationPostsWP\\": "layers/Schema/packages/locationposts-wp/src",
            "PoPSchema\\LocationPosts\\": "layers/Schema/packages/locationposts/src",
            "PoPSchema\\LocationsWPEM\\": "layers/Schema/packages/locations-wp-em/src",
            "PoPSchema\\Locations\\": "layers/Schema/packages/locations/src",
            "PoPSchema\\MediaWP\\": "layers/Schema/packages/media-wp/src",
            "PoPSchema\\Media\\": "layers/Schema/packages/media/src",
            "PoPSchema\\MenusWP\\": "layers/Schema/packages/menus-wp/src",
            "PoPSchema\\Menus\\": "layers/Schema/packages/menus/src",
            "PoPSchema\\MetaQueryWP\\": "layers/Schema/packages/metaquery-wp/src",
            "PoPSchema\\MetaQuery\\": "layers/Schema/packages/metaquery/src",
            "PoPSchema\\Meta\\": "layers/Schema/packages/meta/src",
            "PoPSchema\\NotificationsWP\\": "layers/Schema/packages/notifications-wp/src",
            "PoPSchema\\Notifications\\": "layers/Schema/packages/notifications/src",
            "PoPSchema\\PagesWP\\": "layers/Schema/packages/pages-wp/src",
            "PoPSchema\\Pages\\": "layers/Schema/packages/pages/src",
            "PoPSchema\\PostMutations\\": "layers/Schema/packages/post-mutations/src",
            "PoPSchema\\PostTagsWP\\": "layers/Schema/packages/post-tags-wp/src",
            "PoPSchema\\PostTags\\": "layers/Schema/packages/post-tags/src",
            "PoPSchema\\PostsWP\\": "layers/Schema/packages/posts-wp/src",
            "PoPSchema\\Posts\\": "layers/Schema/packages/posts/src",
            "PoPSchema\\QueriedObjectWP\\": "layers/Schema/packages/queriedobject-wp/src",
            "PoPSchema\\QueriedObject\\": "layers/Schema/packages/queriedobject/src",
            "PoPSchema\\SchemaCommons\\": "layers/Schema/packages/schema-commons/src",
            "PoPSchema\\StancesWP\\": "layers/Schema/packages/stances-wp/src",
            "PoPSchema\\Stances\\": "layers/Schema/packages/stances/src",
            "PoPSchema\\TagsWP\\": "layers/Schema/packages/tags-wp/src",
            "PoPSchema\\Tags\\": "layers/Schema/packages/tags/src",
            "PoPSchema\\TaxonomiesWP\\": "layers/Schema/packages/taxonomies-wp/src",
            "PoPSchema\\Taxonomies\\": "layers/Schema/packages/taxonomies/src",
            "PoPSchema\\TaxonomyMetaWP\\": "layers/Schema/packages/taxonomymeta-wp/src",
            "PoPSchema\\TaxonomyMeta\\": "layers/Schema/packages/taxonomymeta/src",
            "PoPSchema\\TaxonomyQueryWP\\": "layers/Schema/packages/taxonomyquery-wp/src",
            "PoPSchema\\TaxonomyQuery\\": "layers/Schema/packages/taxonomyquery/src",
            "PoPSchema\\TranslateDirectiveACL\\": "layers/Schema/packages/translate-directive-acl/src",
            "PoPSchema\\TranslateDirective\\": "layers/Schema/packages/translate-directive/src",
            "PoPSchema\\UserMetaWP\\": "layers/Schema/packages/usermeta-wp/src",
            "PoPSchema\\UserMeta\\": "layers/Schema/packages/usermeta/src",
            "PoPSchema\\UserRolesACL\\": "layers/Schema/packages/user-roles-acl/src",
            "PoPSchema\\UserRolesAccessControl\\": "layers/Schema/packages/user-roles-access-control/src",
            "PoPSchema\\UserRolesWP\\": "layers/Schema/packages/user-roles-wp/src",
            "PoPSchema\\UserRoles\\": "layers/Schema/packages/user-roles/src",
            "PoPSchema\\UserStateAccessControl\\": "layers/Schema/packages/user-state-access-control/src",
            "PoPSchema\\UserStateMutationsWP\\": "layers/Schema/packages/user-state-mutations-wp/src",
            "PoPSchema\\UserStateMutations\\": "layers/Schema/packages/user-state-mutations/src",
            "PoPSchema\\UserStateWP\\": "layers/Schema/packages/user-state-wp/src",
            "PoPSchema\\UserState\\": "layers/Schema/packages/user-state/src",
            "PoPSchema\\UsersWP\\": "layers/Schema/packages/users-wp/src",
            "PoPSchema\\Users\\": "layers/Schema/packages/users/src",
            "PoPSitesWassup\\CommentMutations\\": "layers/Wassup/packages/comment-mutations/src",
            "PoPSitesWassup\\ContactUsMutations\\": "layers/Wassup/packages/contactus-mutations/src",
            "PoPSitesWassup\\ContactUserMutations\\": "layers/Wassup/packages/contactuser-mutations/src",
            "PoPSitesWassup\\CustomPostLinkMutations\\": "layers/Wassup/packages/custompostlink-mutations/src",
            "PoPSitesWassup\\CustomPostMutations\\": "layers/Wassup/packages/custompost-mutations/src",
            "PoPSitesWassup\\EventLinkMutations\\": "layers/Wassup/packages/eventlink-mutations/src",
            "PoPSitesWassup\\EventMutations\\": "layers/Wassup/packages/event-mutations/src",
            "PoPSitesWassup\\EverythingElseMutations\\": "layers/Wassup/packages/everythingelse-mutations/src",
            "PoPSitesWassup\\FlagMutations\\": "layers/Wassup/packages/flag-mutations/src",
            "PoPSitesWassup\\FormMutations\\": "layers/Wassup/packages/form-mutations/src",
            "PoPSitesWassup\\GravityFormsMutations\\": "layers/Wassup/packages/gravityforms-mutations/src",
            "PoPSitesWassup\\HighlightMutations\\": "layers/Wassup/packages/highlight-mutations/src",
            "PoPSitesWassup\\LocationMutations\\": "layers/Wassup/packages/location-mutations/src",
            "PoPSitesWassup\\LocationPostLinkMutations\\": "layers/Wassup/packages/locationpostlink-mutations/src",
            "PoPSitesWassup\\LocationPostMutations\\": "layers/Wassup/packages/locationpost-mutations/src",
            "PoPSitesWassup\\NewsletterMutations\\": "layers/Wassup/packages/newsletter-mutations/src",
            "PoPSitesWassup\\NotificationMutations\\": "layers/Wassup/packages/notification-mutations/src",
            "PoPSitesWassup\\PostLinkMutations\\": "layers/Wassup/packages/postlink-mutations/src",
            "PoPSitesWassup\\PostMutations\\": "layers/Wassup/packages/post-mutations/src",
            "PoPSitesWassup\\ShareMutations\\": "layers/Wassup/packages/share-mutations/src",
            "PoPSitesWassup\\SocialNetworkMutations\\": "layers/Wassup/packages/socialnetwork-mutations/src",
            "PoPSitesWassup\\StanceMutations\\": "layers/Wassup/packages/stance-mutations/src",
            "PoPSitesWassup\\SystemMutations\\": "layers/Wassup/packages/system-mutations/src",
            "PoPSitesWassup\\UserStateMutations\\": "layers/Wassup/packages/user-state-mutations/src",
            "PoPSitesWassup\\VolunteerMutations\\": "layers/Wassup/packages/volunteer-mutations/src",
            "PoPSitesWassup\\Wassup\\": "layers/Wassup/packages/wassup/src",
            "PoP\\APIClients\\": "layers/API/packages/api-clients/src",
            "PoP\\APIEndpointsForWP\\": "layers/API/packages/api-endpoints-for-wp/src",
            "PoP\\APIEndpoints\\": "layers/API/packages/api-endpoints/src",
            "PoP\\APIMirrorQuery\\": "layers/API/packages/api-mirrorquery/src",
            "PoP\\API\\": "layers/API/packages/api/src",
            "PoP\\AccessControl\\": "layers/Engine/packages/access-control/src",
            "PoP\\ApplicationWP\\": "layers/SiteBuilder/packages/application-wp/src",
            "PoP\\Application\\": "layers/SiteBuilder/packages/application/src",
            "PoP\\Base36Definitions\\": "layers/SiteBuilder/packages/definitions-base36/src",
            "PoP\\CacheControl\\": "layers/Engine/packages/cache-control/src",
            "PoP\\ComponentModel\\": "layers/Engine/packages/component-model/src",
            "PoP\\ConfigurableSchemaFeedback\\": "layers/Engine/packages/configurable-schema-feedback/src",
            "PoP\\ConfigurationComponentModel\\": "layers/SiteBuilder/packages/component-model-configuration/src",
            "PoP\\DefinitionPersistence\\": "layers/SiteBuilder/packages/definitionpersistence/src",
            "PoP\\Definitions\\": "layers/Engine/packages/definitions/src",
            "PoP\\EmojiDefinitions\\": "layers/SiteBuilder/packages/definitions-emoji/src",
            "PoP\\EngineWP\\": "layers/Engine/packages/engine-wp/src",
            "PoP\\Engine\\": "layers/Engine/packages/engine/src",
            "PoP\\FieldQuery\\": "layers/Engine/packages/field-query/src",
            "PoP\\FileStore\\": "layers/Engine/packages/filestore/src",
            "PoP\\FunctionFields\\": "layers/Engine/packages/function-fields/src",
            "PoP\\GraphQLAPI\\": "layers/API/packages/api-graphql/src",
            "PoP\\GuzzleHelpers\\": "layers/Engine/packages/guzzle-helpers/src",
            "PoP\\HooksWP\\": "layers/Engine/packages/hooks-wp/src",
            "PoP\\Hooks\\": "layers/Engine/packages/hooks/src",
            "PoP\\LooseContracts\\": "layers/Engine/packages/loosecontracts/src",
            "PoP\\MandatoryDirectivesByConfiguration\\": "layers/Engine/packages/mandatory-directives-by-configuration/src",
            "PoP\\ModuleRouting\\": "layers/Engine/packages/modulerouting/src",
            "PoP\\Multisite\\": "layers/SiteBuilder/packages/multisite/src",
            "PoP\\PoP\\": "src",
            "PoP\\QueryParsing\\": "layers/Engine/packages/query-parsing/src",
            "PoP\\RESTAPI\\": "layers/API/packages/api-rest/src",
            "PoP\\ResourceLoader\\": "layers/SiteBuilder/packages/resourceloader/src",
            "PoP\\Resources\\": "layers/SiteBuilder/packages/resources/src",
            "PoP\\Root\\": "layers/Engine/packages/root/src",
            "PoP\\RoutingWP\\": "layers/Engine/packages/routing-wp/src",
            "PoP\\Routing\\": "layers/Engine/packages/routing/src",
            "PoP\\SPA\\": "layers/SiteBuilder/packages/spa/src",
            "PoP\\SSG\\": "layers/SiteBuilder/packages/static-site-generator/src",
            "PoP\\SiteWP\\": "layers/SiteBuilder/packages/site-wp/src",
            "PoP\\Site\\": "layers/SiteBuilder/packages/site/src",
            "PoP\\TraceTools\\": "layers/Engine/packages/trace-tools/src",
            "PoP\\TranslationWP\\": "layers/Engine/packages/translation-wp/src",
            "PoP\\Translation\\": "layers/Engine/packages/translation/src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "GraphQLAPI\\ConvertCaseDirectives\\": "layers/GraphQLAPIForWP/plugins/convert-case-directives/tests",
            "GraphQLAPI\\GraphQLAPI\\": "layers/GraphQLAPIForWP/plugins/graphql-api-for-wp/tests",
            "GraphQLAPI\\SchemaFeedback\\": "layers/GraphQLAPIForWP/plugins/schema-feedback/tests",
            "GraphQLByPoP\\GraphQLClientsForWP\\": "layers/GraphQLByPoP/packages/graphql-clients-for-wp/tests",
            "GraphQLByPoP\\GraphQLEndpointForWP\\": "layers/GraphQLByPoP/packages/graphql-endpoint-for-wp/tests",
            "GraphQLByPoP\\GraphQLParser\\": "layers/GraphQLByPoP/packages/graphql-parser/tests",
            "GraphQLByPoP\\GraphQLQuery\\": "layers/GraphQLByPoP/packages/graphql-query/tests",
            "GraphQLByPoP\\GraphQLRequest\\": "layers/GraphQLByPoP/packages/graphql-request/tests",
            "GraphQLByPoP\\GraphQLServer\\": "layers/GraphQLByPoP/packages/graphql-server/tests",
            "Leoloso\\ExamplesForPoP\\": "layers/Misc/packages/examples-for-pop/tests",
            "PoPSchema\\BasicDirectives\\": "layers/Schema/packages/basic-directives/tests",
            "PoPSchema\\BlockMetadataWP\\": "layers/Schema/packages/block-metadata-for-wp/tests",
            "PoPSchema\\CDNDirective\\": "layers/Schema/packages/cdn-directive/tests",
            "PoPSchema\\CategoriesWP\\": "layers/Schema/packages/categories-wp/tests",
            "PoPSchema\\Categories\\": "layers/Schema/packages/categories/tests",
            "PoPSchema\\CommentMetaWP\\": "layers/Schema/packages/commentmeta-wp/tests",
            "PoPSchema\\CommentMeta\\": "layers/Schema/packages/commentmeta/tests",
            "PoPSchema\\CommentMutationsWP\\": "layers/Schema/packages/comment-mutations-wp/tests",
            "PoPSchema\\CommentMutations\\": "layers/Schema/packages/comment-mutations/tests",
            "PoPSchema\\CommentsWP\\": "layers/Schema/packages/comments-wp/tests",
            "PoPSchema\\Comments\\": "layers/Schema/packages/comments/tests",
            "PoPSchema\\ConvertCaseDirectives\\": "layers/Schema/packages/convert-case-directives/tests",
            "PoPSchema\\CustomPostMediaMutationsWP\\": "layers/Schema/packages/custompostmedia-mutations-wp/tests",
            "PoPSchema\\CustomPostMediaMutations\\": "layers/Schema/packages/custompostmedia-mutations/tests",
            "PoPSchema\\CustomPostMediaWP\\": "layers/Schema/packages/custompostmedia-wp/tests",
            "PoPSchema\\CustomPostMedia\\": "layers/Schema/packages/custompostmedia/tests",
            "PoPSchema\\CustomPostMetaWP\\": "layers/Schema/packages/custompostmeta-wp/tests",
            "PoPSchema\\CustomPostMeta\\": "layers/Schema/packages/custompostmeta/tests",
            "PoPSchema\\CustomPostMutationsWP\\": "layers/Schema/packages/custompost-mutations-wp/tests",
            "PoPSchema\\CustomPostMutations\\": "layers/Schema/packages/custompost-mutations/tests",
            "PoPSchema\\CustomPostsWP\\": "layers/Schema/packages/customposts-wp/tests",
            "PoPSchema\\CustomPosts\\": "layers/Schema/packages/customposts/tests",
            "PoPSchema\\EventMutationsWPEM\\": "layers/Schema/packages/event-mutations-wp-em/tests",
            "PoPSchema\\EventMutations\\": "layers/Schema/packages/event-mutations/tests",
            "PoPSchema\\EventsWPEM\\": "layers/Schema/packages/events-wp-em/tests",
            "PoPSchema\\Events\\": "layers/Schema/packages/events/tests",
            "PoPSchema\\EverythingElseWP\\": "layers/Schema/packages/everythingelse-wp/tests",
            "PoPSchema\\EverythingElse\\": "layers/Schema/packages/everythingelse/tests",
            "PoPSchema\\GenericCustomPosts\\": "layers/Schema/packages/generic-customposts/tests",
            "PoPSchema\\GoogleTranslateDirectiveForCustomPosts\\": "layers/Schema/packages/google-translate-directive-for-customposts/tests",
            "PoPSchema\\GoogleTranslateDirective\\": "layers/Schema/packages/google-translate-directive/tests",
            "PoPSchema\\HighlightsWP\\": "layers/Schema/packages/highlights-wp/tests",
            "PoPSchema\\Highlights\\": "layers/Schema/packages/highlights/tests",
            "PoPSchema\\LocationPostsWP\\": "layers/Schema/packages/locationposts-wp/tests",
            "PoPSchema\\LocationPosts\\": "layers/Schema/packages/locationposts/tests",
            "PoPSchema\\LocationsWPEM\\": "layers/Schema/packages/locations-wp-em/tests",
            "PoPSchema\\Locations\\": "layers/Schema/packages/locations/tests",
            "PoPSchema\\MediaWP\\": "layers/Schema/packages/media-wp/tests",
            "PoPSchema\\Media\\": "layers/Schema/packages/media/tests",
            "PoPSchema\\MenusWP\\": "layers/Schema/packages/menus-wp/tests",
            "PoPSchema\\Menus\\": "layers/Schema/packages/menus/tests",
            "PoPSchema\\MetaQueryWP\\": "layers/Schema/packages/metaquery-wp/tests",
            "PoPSchema\\MetaQuery\\": "layers/Schema/packages/metaquery/tests",
            "PoPSchema\\Meta\\": "layers/Schema/packages/meta/tests",
            "PoPSchema\\NotificationsWP\\": "layers/Schema/packages/notifications-wp/tests",
            "PoPSchema\\Notifications\\": "layers/Schema/packages/notifications/tests",
            "PoPSchema\\PagesWP\\": "layers/Schema/packages/pages-wp/tests",
            "PoPSchema\\Pages\\": "layers/Schema/packages/pages/tests",
            "PoPSchema\\PostMutations\\": "layers/Schema/packages/post-mutations/tests",
            "PoPSchema\\PostTagsWP\\": "layers/Schema/packages/post-tags-wp/tests",
            "PoPSchema\\PostTags\\": "layers/Schema/packages/post-tags/tests",
            "PoPSchema\\PostsWP\\": "layers/Schema/packages/posts-wp/tests",
            "PoPSchema\\Posts\\": "layers/Schema/packages/posts/tests",
            "PoPSchema\\QueriedObjectWP\\": "layers/Schema/packages/queriedobject-wp/tests",
            "PoPSchema\\QueriedObject\\": "layers/Schema/packages/queriedobject/tests",
            "PoPSchema\\SchemaCommons\\": "layers/Schema/packages/schema-commons/tests",
            "PoPSchema\\StancesWP\\": "layers/Schema/packages/stances-wp/tests",
            "PoPSchema\\Stances\\": "layers/Schema/packages/stances/tests",
            "PoPSchema\\TagsWP\\": "layers/Schema/packages/tags-wp/tests",
            "PoPSchema\\Tags\\": "layers/Schema/packages/tags/tests",
            "PoPSchema\\TaxonomiesWP\\": "layers/Schema/packages/taxonomies-wp/tests",
            "PoPSchema\\Taxonomies\\": "layers/Schema/packages/taxonomies/tests",
            "PoPSchema\\TaxonomyMetaWP\\": "layers/Schema/packages/taxonomymeta-wp/tests",
            "PoPSchema\\TaxonomyMeta\\": "layers/Schema/packages/taxonomymeta/tests",
            "PoPSchema\\TaxonomyQueryWP\\": "layers/Schema/packages/taxonomyquery-wp/tests",
            "PoPSchema\\TaxonomyQuery\\": "layers/Schema/packages/taxonomyquery/tests",
            "PoPSchema\\TranslateDirectiveACL\\": "layers/Schema/packages/translate-directive-acl/tests",
            "PoPSchema\\TranslateDirective\\": "layers/Schema/packages/translate-directive/tests",
            "PoPSchema\\UserMetaWP\\": "layers/Schema/packages/usermeta-wp/tests",
            "PoPSchema\\UserMeta\\": "layers/Schema/packages/usermeta/tests",
            "PoPSchema\\UserRolesACL\\": "layers/Schema/packages/user-roles-acl/tests",
            "PoPSchema\\UserRolesAccessControl\\": "layers/Schema/packages/user-roles-access-control/tests",
            "PoPSchema\\UserRolesWP\\": "layers/Schema/packages/user-roles-wp/tests",
            "PoPSchema\\UserRoles\\": "layers/Schema/packages/user-roles/tests",
            "PoPSchema\\UserStateAccessControl\\": "layers/Schema/packages/user-state-access-control/tests",
            "PoPSchema\\UserStateMutationsWP\\": "layers/Schema/packages/user-state-mutations-wp/tests",
            "PoPSchema\\UserStateMutations\\": "layers/Schema/packages/user-state-mutations/tests",
            "PoPSchema\\UserStateWP\\": "layers/Schema/packages/user-state-wp/tests",
            "PoPSchema\\UserState\\": "layers/Schema/packages/user-state/tests",
            "PoPSchema\\UsersWP\\": "layers/Schema/packages/users-wp/tests",
            "PoPSchema\\Users\\": "layers/Schema/packages/users/tests",
            "PoPSitesWassup\\CommentMutations\\": "layers/Wassup/packages/comment-mutations/tests",
            "PoPSitesWassup\\ContactUsMutations\\": "layers/Wassup/packages/contactus-mutations/tests",
            "PoPSitesWassup\\ContactUserMutations\\": "layers/Wassup/packages/contactuser-mutations/tests",
            "PoPSitesWassup\\CustomPostLinkMutations\\": "layers/Wassup/packages/custompostlink-mutations/tests",
            "PoPSitesWassup\\CustomPostMutations\\": "layers/Wassup/packages/custompost-mutations/tests",
            "PoPSitesWassup\\EventLinkMutations\\": "layers/Wassup/packages/eventlink-mutations/tests",
            "PoPSitesWassup\\EventMutations\\": "layers/Wassup/packages/event-mutations/tests",
            "PoPSitesWassup\\EverythingElseMutations\\": "layers/Wassup/packages/everythingelse-mutations/tests",
            "PoPSitesWassup\\FlagMutations\\": "layers/Wassup/packages/flag-mutations/tests",
            "PoPSitesWassup\\FormMutations\\": "layers/Wassup/packages/form-mutations/tests",
            "PoPSitesWassup\\GravityFormsMutations\\": "layers/Wassup/packages/gravityforms-mutations/tests",
            "PoPSitesWassup\\HighlightMutations\\": "layers/Wassup/packages/highlight-mutations/tests",
            "PoPSitesWassup\\LocationMutations\\": "layers/Wassup/packages/location-mutations/tests",
            "PoPSitesWassup\\LocationPostLinkMutations\\": "layers/Wassup/packages/locationpostlink-mutations/tests",
            "PoPSitesWassup\\LocationPostMutations\\": "layers/Wassup/packages/locationpost-mutations/tests",
            "PoPSitesWassup\\NewsletterMutations\\": "layers/Wassup/packages/newsletter-mutations/tests",
            "PoPSitesWassup\\NotificationMutations\\": "layers/Wassup/packages/notification-mutations/tests",
            "PoPSitesWassup\\PostLinkMutations\\": "layers/Wassup/packages/postlink-mutations/tests",
            "PoPSitesWassup\\PostMutations\\": "layers/Wassup/packages/post-mutations/tests",
            "PoPSitesWassup\\ShareMutations\\": "layers/Wassup/packages/share-mutations/tests",
            "PoPSitesWassup\\SocialNetworkMutations\\": "layers/Wassup/packages/socialnetwork-mutations/tests",
            "PoPSitesWassup\\StanceMutations\\": "layers/Wassup/packages/stance-mutations/tests",
            "PoPSitesWassup\\SystemMutations\\": "layers/Wassup/packages/system-mutations/tests",
            "PoPSitesWassup\\UserStateMutations\\": "layers/Wassup/packages/user-state-mutations/tests",
            "PoPSitesWassup\\VolunteerMutations\\": "layers/Wassup/packages/volunteer-mutations/tests",
            "PoPSitesWassup\\Wassup\\": "layers/Wassup/packages/wassup/tests",
            "PoP\\APIClients\\": "layers/API/packages/api-clients/tests",
            "PoP\\APIEndpointsForWP\\": "layers/API/packages/api-endpoints-for-wp/tests",
            "PoP\\APIEndpoints\\": "layers/API/packages/api-endpoints/tests",
            "PoP\\APIMirrorQuery\\": "layers/API/packages/api-mirrorquery/tests",
            "PoP\\API\\": "layers/API/packages/api/tests",
            "PoP\\AccessControl\\": "layers/Engine/packages/access-control/tests",
            "PoP\\ApplicationWP\\": "layers/SiteBuilder/packages/application-wp/tests",
            "PoP\\Application\\": "layers/SiteBuilder/packages/application/tests",
            "PoP\\Base36Definitions\\": "layers/SiteBuilder/packages/definitions-base36/tests",
            "PoP\\CacheControl\\": "layers/Engine/packages/cache-control/tests",
            "PoP\\ComponentModel\\": "layers/Engine/packages/component-model/tests",
            "PoP\\ConfigurableSchemaFeedback\\": "layers/Engine/packages/configurable-schema-feedback/tests",
            "PoP\\ConfigurationComponentModel\\": "layers/SiteBuilder/packages/component-model-configuration/tests",
            "PoP\\DefinitionPersistence\\": "layers/SiteBuilder/packages/definitionpersistence/tests",
            "PoP\\Definitions\\": "layers/Engine/packages/definitions/tests",
            "PoP\\EmojiDefinitions\\": "layers/SiteBuilder/packages/definitions-emoji/tests",
            "PoP\\EngineWP\\": "layers/Engine/packages/engine-wp/tests",
            "PoP\\Engine\\": "layers/Engine/packages/engine/tests",
            "PoP\\FieldQuery\\": "layers/Engine/packages/field-query/tests",
            "PoP\\FileStore\\": "layers/Engine/packages/filestore/tests",
            "PoP\\FunctionFields\\": "layers/Engine/packages/function-fields/tests",
            "PoP\\GraphQLAPI\\": "layers/API/packages/api-graphql/tests",
            "PoP\\GuzzleHelpers\\": "layers/Engine/packages/guzzle-helpers/tests",
            "PoP\\HooksWP\\": "layers/Engine/packages/hooks-wp/tests",
            "PoP\\Hooks\\": "layers/Engine/packages/hooks/tests",
            "PoP\\LooseContracts\\": "layers/Engine/packages/loosecontracts/tests",
            "PoP\\MandatoryDirectivesByConfiguration\\": "layers/Engine/packages/mandatory-directives-by-configuration/tests",
            "PoP\\ModuleRouting\\": "layers/Engine/packages/modulerouting/tests",
            "PoP\\Multisite\\": "layers/SiteBuilder/packages/multisite/tests",
            "PoP\\QueryParsing\\": "layers/Engine/packages/query-parsing/tests",
            "PoP\\RESTAPI\\": "layers/API/packages/api-rest/tests",
            "PoP\\ResourceLoader\\": "layers/SiteBuilder/packages/resourceloader/tests",
            "PoP\\Resources\\": "layers/SiteBuilder/packages/resources/tests",
            "PoP\\Root\\": "layers/Engine/packages/root/tests",
            "PoP\\RoutingWP\\": "layers/Engine/packages/routing-wp/tests",
            "PoP\\Routing\\": "layers/Engine/packages/routing/tests",
            "PoP\\SPA\\": "layers/SiteBuilder/packages/spa/tests",
            "PoP\\SSG\\": "layers/SiteBuilder/packages/static-site-generator/tests",
            "PoP\\SiteWP\\": "layers/SiteBuilder/packages/site-wp/tests",
            "PoP\\Site\\": "layers/SiteBuilder/packages/site/tests",
            "PoP\\TraceTools\\": "layers/Engine/packages/trace-tools/tests",
            "PoP\\TranslationWP\\": "layers/Engine/packages/translation-wp/tests",
            "PoP\\Translation\\": "layers/Engine/packages/translation/tests"
        }
    },
    "extra": {
        "wordpress-install-dir": "vendor/wordpress/wordpress",
        "merge-plugin": {
            "include": [
                "composer.local.json"
            ],
            "recurse": true,
            "replace": false,
            "ignore-duplicates": false,
            "merge-dev": true,
            "merge-extra": false,
            "merge-extra-deep": false,
            "merge-scripts": false
        }
    },
    "replace": {
        "getpop/access-control": "self.version",
        "getpop/api": "self.version",
        "getpop/api-clients": "self.version",
        "getpop/api-endpoints": "self.version",
        "getpop/api-endpoints-for-wp": "self.version",
        "getpop/api-graphql": "self.version",
        "getpop/api-mirrorquery": "self.version",
        "getpop/api-rest": "self.version",
        "getpop/application": "self.version",
        "getpop/application-wp": "self.version",
        "getpop/cache-control": "self.version",
        "getpop/component-model": "self.version",
        "getpop/component-model-configuration": "self.version",
        "getpop/configurable-schema-feedback": "self.version",
        "getpop/definitionpersistence": "self.version",
        "getpop/definitions": "self.version",
        "getpop/definitions-base36": "self.version",
        "getpop/definitions-emoji": "self.version",
        "getpop/engine": "self.version",
        "getpop/engine-wp": "self.version",
        "getpop/engine-wp-bootloader": "self.version",
        "getpop/field-query": "self.version",
        "getpop/filestore": "self.version",
        "getpop/function-fields": "self.version",
        "getpop/guzzle-helpers": "self.version",
        "getpop/hooks": "self.version",
        "getpop/hooks-wp": "self.version",
        "getpop/loosecontracts": "self.version",
        "getpop/mandatory-directives-by-configuration": "self.version",
        "getpop/migrate-api": "self.version",
        "getpop/migrate-api-graphql": "self.version",
        "getpop/migrate-component-model": "self.version",
        "getpop/migrate-component-model-configuration": "self.version",
        "getpop/migrate-engine": "self.version",
        "getpop/migrate-engine-wp": "self.version",
        "getpop/migrate-static-site-generator": "self.version",
        "getpop/modulerouting": "self.version",
        "getpop/multisite": "self.version",
        "getpop/query-parsing": "self.version",
        "getpop/resourceloader": "self.version",
        "getpop/resources": "self.version",
        "getpop/root": "self.version",
        "getpop/routing": "self.version",
        "getpop/routing-wp": "self.version",
        "getpop/site": "self.version",
        "getpop/site-wp": "self.version",
        "getpop/spa": "self.version",
        "getpop/static-site-generator": "self.version",
        "getpop/trace-tools": "self.version",
        "getpop/translation": "self.version",
        "getpop/translation-wp": "self.version",
        "graphql-api/convert-case-directives": "self.version",
        "graphql-api/graphql-api-for-wp": "self.version",
        "graphql-api/schema-feedback": "self.version",
        "graphql-by-pop/graphql-clients-for-wp": "self.version",
        "graphql-by-pop/graphql-endpoint-for-wp": "self.version",
        "graphql-by-pop/graphql-parser": "self.version",
        "graphql-by-pop/graphql-query": "self.version",
        "graphql-by-pop/graphql-request": "self.version",
        "graphql-by-pop/graphql-server": "self.version",
        "leoloso/examples-for-pop": "self.version",
        "pop-migrate-everythingelse/cssconverter": "self.version",
        "pop-migrate-everythingelse/ssr": "self.version",
        "pop-schema/basic-directives": "self.version",
        "pop-schema/block-metadata-for-wp": "self.version",
        "pop-schema/categories": "self.version",
        "pop-schema/categories-wp": "self.version",
        "pop-schema/cdn-directive": "self.version",
        "pop-schema/comment-mutations": "self.version",
        "pop-schema/comment-mutations-wp": "self.version",
        "pop-schema/commentmeta": "self.version",
        "pop-schema/commentmeta-wp": "self.version",
        "pop-schema/comments": "self.version",
        "pop-schema/comments-wp": "self.version",
        "pop-schema/convert-case-directives": "self.version",
        "pop-schema/custompost-mutations": "self.version",
        "pop-schema/custompost-mutations-wp": "self.version",
        "pop-schema/custompostmedia": "self.version",
        "pop-schema/custompostmedia-mutations": "self.version",
        "pop-schema/custompostmedia-mutations-wp": "self.version",
        "pop-schema/custompostmedia-wp": "self.version",
        "pop-schema/custompostmeta": "self.version",
        "pop-schema/custompostmeta-wp": "self.version",
        "pop-schema/customposts": "self.version",
        "pop-schema/customposts-wp": "self.version",
        "pop-schema/event-mutations": "self.version",
        "pop-schema/event-mutations-wp-em": "self.version",
        "pop-schema/events": "self.version",
        "pop-schema/events-wp-em": "self.version",
        "pop-schema/everythingelse": "self.version",
        "pop-schema/everythingelse-wp": "self.version",
        "pop-schema/generic-customposts": "self.version",
        "pop-schema/google-translate-directive": "self.version",
        "pop-schema/google-translate-directive-for-customposts": "self.version",
        "pop-schema/highlights": "self.version",
        "pop-schema/highlights-wp": "self.version",
        "pop-schema/locationposts": "self.version",
        "pop-schema/locationposts-wp": "self.version",
        "pop-schema/locations": "self.version",
        "pop-schema/locations-wp-em": "self.version",
        "pop-schema/media": "self.version",
        "pop-schema/media-wp": "self.version",
        "pop-schema/menus": "self.version",
        "pop-schema/menus-wp": "self.version",
        "pop-schema/meta": "self.version",
        "pop-schema/metaquery": "self.version",
        "pop-schema/metaquery-wp": "self.version",
        "pop-schema/migrate-categories": "self.version",
        "pop-schema/migrate-categories-wp": "self.version",
        "pop-schema/migrate-commentmeta": "self.version",
        "pop-schema/migrate-commentmeta-wp": "self.version",
        "pop-schema/migrate-comments": "self.version",
        "pop-schema/migrate-comments-wp": "self.version",
        "pop-schema/migrate-custompostmedia": "self.version",
        "pop-schema/migrate-custompostmedia-wp": "self.version",
        "pop-schema/migrate-custompostmeta": "self.version",
        "pop-schema/migrate-custompostmeta-wp": "self.version",
        "pop-schema/migrate-customposts": "self.version",
        "pop-schema/migrate-customposts-wp": "self.version",
        "pop-schema/migrate-events": "self.version",
        "pop-schema/migrate-events-wp-em": "self.version",
        "pop-schema/migrate-everythingelse": "self.version",
        "pop-schema/migrate-locations": "self.version",
        "pop-schema/migrate-locations-wp-em": "self.version",
        "pop-schema/migrate-media": "self.version",
        "pop-schema/migrate-media-wp": "self.version",
        "pop-schema/migrate-meta": "self.version",
        "pop-schema/migrate-metaquery": "self.version",
        "pop-schema/migrate-metaquery-wp": "self.version",
        "pop-schema/migrate-pages": "self.version",
        "pop-schema/migrate-pages-wp": "self.version",
        "pop-schema/migrate-post-tags": "self.version",
        "pop-schema/migrate-post-tags-wp": "self.version",
        "pop-schema/migrate-posts": "self.version",
        "pop-schema/migrate-posts-wp": "self.version",
        "pop-schema/migrate-queriedobject": "self.version",
        "pop-schema/migrate-queriedobject-wp": "self.version",
        "pop-schema/migrate-tags": "self.version",
        "pop-schema/migrate-tags-wp": "self.version",
        "pop-schema/migrate-taxonomies": "self.version",
        "pop-schema/migrate-taxonomies-wp": "self.version",
        "pop-schema/migrate-taxonomymeta": "self.version",
        "pop-schema/migrate-taxonomymeta-wp": "self.version",
        "pop-schema/migrate-taxonomyquery": "self.version",
        "pop-schema/migrate-taxonomyquery-wp": "self.version",
        "pop-schema/migrate-usermeta": "self.version",
        "pop-schema/migrate-usermeta-wp": "self.version",
        "pop-schema/migrate-users": "self.version",
        "pop-schema/migrate-users-wp": "self.version",
        "pop-schema/notifications": "self.version",
        "pop-schema/notifications-wp": "self.version",
        "pop-schema/pages": "self.version",
        "pop-schema/pages-wp": "self.version",
        "pop-schema/post-mutations": "self.version",
        "pop-schema/post-tags": "self.version",
        "pop-schema/post-tags-wp": "self.version",
        "pop-schema/posts": "self.version",
        "pop-schema/posts-wp": "self.version",
        "pop-schema/queriedobject": "self.version",
        "pop-schema/queriedobject-wp": "self.version",
        "pop-schema/schema-commons": "self.version",
        "pop-schema/stances": "self.version",
        "pop-schema/stances-wp": "self.version",
        "pop-schema/tags": "self.version",
        "pop-schema/tags-wp": "self.version",
        "pop-schema/taxonomies": "self.version",
        "pop-schema/taxonomies-wp": "self.version",
        "pop-schema/taxonomymeta": "self.version",
        "pop-schema/taxonomymeta-wp": "self.version",
        "pop-schema/taxonomyquery": "self.version",
        "pop-schema/taxonomyquery-wp": "self.version",
        "pop-schema/translate-directive": "self.version",
        "pop-schema/translate-directive-acl": "self.version",
        "pop-schema/user-roles": "self.version",
        "pop-schema/user-roles-access-control": "self.version",
        "pop-schema/user-roles-acl": "self.version",
        "pop-schema/user-roles-wp": "self.version",
        "pop-schema/user-state": "self.version",
        "pop-schema/user-state-access-control": "self.version",
        "pop-schema/user-state-mutations": "self.version",
        "pop-schema/user-state-mutations-wp": "self.version",
        "pop-schema/user-state-wp": "self.version",
        "pop-schema/usermeta": "self.version",
        "pop-schema/usermeta-wp": "self.version",
        "pop-schema/users": "self.version",
        "pop-schema/users-wp": "self.version",
        "pop-sites-wassup/comment-mutations": "self.version",
        "pop-sites-wassup/contactus-mutations": "self.version",
        "pop-sites-wassup/contactuser-mutations": "self.version",
        "pop-sites-wassup/custompost-mutations": "self.version",
        "pop-sites-wassup/custompostlink-mutations": "self.version",
        "pop-sites-wassup/event-mutations": "self.version",
        "pop-sites-wassup/eventlink-mutations": "self.version",
        "pop-sites-wassup/everythingelse-mutations": "self.version",
        "pop-sites-wassup/flag-mutations": "self.version",
        "pop-sites-wassup/form-mutations": "self.version",
        "pop-sites-wassup/gravityforms-mutations": "self.version",
        "pop-sites-wassup/highlight-mutations": "self.version",
        "pop-sites-wassup/location-mutations": "self.version",
        "pop-sites-wassup/locationpost-mutations": "self.version",
        "pop-sites-wassup/locationpostlink-mutations": "self.version",
        "pop-sites-wassup/newsletter-mutations": "self.version",
        "pop-sites-wassup/notification-mutations": "self.version",
        "pop-sites-wassup/post-mutations": "self.version",
        "pop-sites-wassup/postlink-mutations": "self.version",
        "pop-sites-wassup/share-mutations": "self.version",
        "pop-sites-wassup/socialnetwork-mutations": "self.version",
        "pop-sites-wassup/stance-mutations": "self.version",
        "pop-sites-wassup/system-mutations": "self.version",
        "pop-sites-wassup/user-state-mutations": "self.version",
        "pop-sites-wassup/volunteer-mutations": "self.version",
        "pop-sites-wassup/wassup": "self.version"
    },
    "authors": [
        {
            "name": "Leonardo Losoviz",
            "email": "leo@getpop.org",
            "homepage": "https://getpop.org"
        }
    ],
    "description": "Monorepo for all the PoP packages",
    "license": "GPL-2.0-or-later",
    "config": {
        "sort-packages": true
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://wpackagist.org"
        },
        {
            "type": "vcs",
            "url": "https://github.com/leoloso/wp-muplugin-loader.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/mcaskill/composer-merge-plugin.git"
        }
    ],
    "scripts": {
        "test": "phpunit",
        "check-style": "phpcs -n src $(monorepo-builder source-packages --subfolder=src --subfolder=tests)",
        "fix-style": "phpcbf -n src $(monorepo-builder source-packages --subfolder=src --subfolder=tests)",
        "analyse": "ci/phpstan.sh \". $(monorepo-builder source-packages --skip-unmigrated)\"",
        "preview-src-downgrade": "rector process $(monorepo-builder source-packages --subfolder=src) --config=rector-downgrade-code.php --ansi --dry-run || true",
        "preview-vendor-downgrade": "layers/Engine/packages/root/ci/downgrade_code.sh 7.1 rector-downgrade-code.php --dry-run || true",
        "preview-code-downgrade": [
            "@preview-src-downgrade",
            "@preview-vendor-downgrade"
        ],
        "build-server": [
            "lando init --source remote --remote-url https://wordpress.org/latest.tar.gz --recipe wordpress --webroot wordpress --name graphql-api-dev",
            "@start-server"
        ],
        "start-server": [
            "cd layers/GraphQLAPIForWP/plugins/graphql-api-for-wp && composer install",
            "lando start"
        ],
        "rebuild-server": "lando rebuild -y",
        "merge-monorepo": "monorepo-builder merge --ansi",
        "propagate-monorepo": "monorepo-builder propagate --ansi",
        "validate-monorepo": "monorepo-builder validate --ansi",
        "release": "monorepo-builder release patch --ansi"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.8
PHP version: 7.4.13
PHP binary path: /usr/local/Cellar/php@7.4/7.4.13_1/bin/php
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
cURL version: 7.73.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1h
zip: extension present, unzip present
```

When I run this command: 

```bash
composer config platform-check false -vvv
```

I get the following output: 

```
Reading ./composer.json
Loading config file /Users/mac/.composer/auth.json
Loading config file ./composer.json
Checked CA file /usr/local/etc/openssl@1.1/cert.pem: valid
Executing command (/Users/mac/GitRepos/GitHub/Projects/leoloso/PoP): git branch -a --no-color --no-abbrev -v
Executing command (/Users/mac/GitRepos/GitHub/Projects/leoloso/PoP): git rev-list master..run-downgrade-tests-for-monorepo-root
Executing command (/Users/mac/GitRepos/GitHub/Projects/leoloso/PoP): git rev-list remotes/origin/master..run-downgrade-tests-for-monorepo-root
Reading /Users/mac/.composer/composer.json
Loading config file /Users/mac/.composer/auth.json
Loading config file /Users/mac/.composer/composer.json
Loading config file /Users/mac/.composer/auth.json
Reading /Users/mac/.composer/auth.json
Reading /Users/mac/GitRepos/GitHub/Projects/leoloso/PoP/vendor/composer/installed.json
Reading /Users/mac/.composer/vendor/composer/installed.json
Loading plugin PackageVersions\Installer
Loading plugin johnpbloch\Composer\WordPressCorePlugin
Loading plugin Composer\Installers\Plugin
Loading plugin LkWdwrd\Composer\MULoaderPlugin
Running 2.0.8 (2020-12-03 17:20:38) with PHP 7.4.13 on Darwin / 19.6.0
Loading config file /Users/mac/.composer/auth.json
Reading ./composer.json

                                                      
  [RuntimeException]                                  
  Failed to execute regex: PREG_JIT_STACKLIMIT_ERROR  
                                                      

Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Json/JsonManipulator.php:552
 Composer\Json\JsonManipulator->pregMatch() at phar:///usr/local/bin/composer/src/Composer/Json/JsonManipulator.php:227
 Composer\Json\JsonManipulator->addSubNode() at phar:///usr/local/bin/composer/src/Composer/Json/JsonManipulator.php:160
 Composer\Json\JsonManipulator->addConfigSetting() at n/a:n/a
 call_user_func_array() at phar:///usr/local/bin/composer/src/Composer/Config/JsonConfigSource.php:247
 Composer\Config\JsonConfigSource->manipulateJson() at phar:///usr/local/bin/composer/src/Composer/Config/JsonConfigSource.php:114
 Composer\Config\JsonConfigSource->addConfigSetting() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/composer/src/Composer/Command/ConfigCommand.php:777
 Composer\Command\ConfigCommand->handleSingleValue() at phar:///usr/local/bin/composer/src/Composer/Command/ConfigCommand.php:499
 Composer\Command\ConfigCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:310
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:122
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:63
 require() at /usr/local/bin/composer:24

config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [-j|--json] [-m|--merge] [--append] [--] [<setting-key>] [<setting-value>]...
```

And I expected this to happen:

Well, it should not throw `PREG_JIT_STACKLIMIT_ERROR` 😄

### PR DESCRIPTION
**Pull request by Seldaek**
fixes #9595

### CODE REVIEW

File: src/Composer/Json/JsonManipulator.php [hunk 1]
```diff
@@ -20,13 +20,13 @@
 class JsonManipulator
 {
     private static $DEFINES = '(?(DEFINE)
-       (?<number>   -? (?= [1-9]|0(?!\d) ) \d+ (\.\d+)? ([eE] [+-]? \d+)? )
+       (?<number>    -? (?= [1-9]|0(?!\d) ) \d++ (\.\d++)? ([eE] [+-]? \d++)? )
```
Comment (stof) [inline src/Composer/Json/JsonManipulator.php:23]: the quantifier on `[+-]?` could also become possessive (as the `+` and `-` chars cannot be matched in a different way if they are there, while staying inside the whole optional group.

Also, the whole `[eE] [+-]? \d++` optional group could probably become possessive as well.

File: src/Composer/Json/JsonManipulator.php [hunk 2]
```diff
@@ -20,13 +20,13 @@
...
        (?<boolean>   true | false | null )
-       (?<string>    " ([^"\\\\]* | \\\\ ["\\\\bfnrt\/] | \\\\ u [0-9A-Fa-f]{4} )* " )
-       (?<array>     \[  (?:  (?&json) \s* (?: , (?&json) \s* )*  )?  \s* \] )
-       (?<pair>      \s* (?&string) \s* : (?&json) \s* )
-       (?<object>    \{  (?:  (?&pair)  (?: , (?&pair)  )*  )?  \s* \} )
-       (?<json>   \s* (?: (?&number) | (?&boolean) | (?&string) | (?&array) | (?&object) ) )
+       (?<string>    " ([^"\\\\]*+ | \\\\ ["\\\\bfnrt\/] | \\\\ u [0-9A-Fa-f]{4} )* " )
```
Comment (stof) [inline src/Composer/Json/JsonManipulator.php:25]: the repeated group instead the string quotes can also become possessive

File: src/Composer/Json/JsonManipulator.php [hunk 3]
```diff
@@ -20,13 +20,13 @@
...
+       (?<array>     \[  (?:  (?&json) \s*+ (?: , (?&json) \s*+ )*+  )?  \s*+ \] )
```
Comment (stof) [inline src/Composer/Json/JsonManipulator.php:26]: the optional group can also become possessive. Backtracking over it won't help matching the end of the array in a different way, as there is no way for the `]` to have been matched by the `?$json` reference (there is no valid json starting with that char).

File: src/Composer/Json/JsonManipulator.php [hunk 4]
```diff
@@ -20,13 +20,13 @@
...
+       (?<pair>      \s*+ (?&string) \s*+ : (?&json) \s*+ )
+       (?<object>    \{  (?:  (?&pair)  (?: , (?&pair)  )*+  )?  \s*+ \} )
```
Comment (stof) [inline src/Composer/Json/JsonManipulator.php:28]: the optional block can also be possessive. If a content was matched in the object, backtracking over it won't allow finding the `}` as the pair cannot start with it.

**Review by stof — CHANGES_REQUESTED** [review]

File: src/Composer/Json/JsonManipulator.php (hunk 2 above)
Comment (Seldaek) [reply src/Composer/Json/JsonManipulator.php:25]: Nope, that breaks tests as I believe if it appears it prevent it from using backtracking to continue parsing the rest of the string when parsing some string like "foo\\bar" which does not match in a single pass of the subgroup. See https://regex101.com/r/CBcxyd/1 (removing the last + makes it match)

Comment (stof) [reply src/Composer/Json/JsonManipulator.php:25]: hmm indeed. I forgot how possessive quantifiers behave when applied on repeated alternatives.

**Comment by Seldaek** [comment]
Alright then I guess merging and let's hope we didn't miss anything. Thanks
