### PR TITLE
Remove extra '/' when findShortestPath $from is a directory

### LINKED ISSUE #3024: Composer adding extra '../' in classmap based on $baseDir
In my production environment, when I deploy my app and run `composer install --no-dev`, every Class mapped in `$baseDir` has an extra '../' in path.

```php
<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'AlterFaltasEcode' => $baseDir . '/../app/database/migrations/2014_05_27_171840_alter_faltas_ecode.php',
    'AlterFaltasOrigem' => $baseDir . '/../app/database/migrations/2014_05_27_171906_alter_faltas_origem.php',
    'BaseController' => $baseDir . '/../app/controllers/BaseController.php',
    'Carbon\\Carbon' => $vendorDir . '/nesbot/carbon/src/Carbon/Carbon.php',
    'ClassPreloader\\Application' => $vendorDir . '/classpreloader/classpreloader/src/ClassPreloader/Application.php',
    'ClassPreloader\\ClassList' => $vendorDir . '/classpreloader/classpreloader/src/ClassPreloader/ClassList.php',
    'ClassPreloader\\ClassLoader' => $vendorDir . '/classpreloader/classpreloader/src/ClassPreloader/ClassLoader.php',
'User' => $baseDir . '/app/models/User.php',
    'Whoops\\Exception\\ErrorException' => $vendorDir . '/filp/whoops/src/Whoops/Exception/ErrorException.php',
    'Whoops\\Exception\\Frame' => $vendorDir . '/filp/whoops/src/Whoops/Exception/Frame.php',
    'Whoops\\Exception\\FrameCollection' => $vendorDir . '/filp/whoops/src/Whoops/Exception/FrameCollection.php',
    'Whoops\\Exception\\Inspector' => $vendorDir . '/filp/whoops/src/Whoops/Exception/Inspector.php',
    'Whoops\\Handler\\CallbackHandler' => $vendorDir . '/filp/whoops/src/Whoops/Handler/CallbackHandler.php',
    'Whoops\\Handler\\Handler' => $vendorDir . '/filp/whoops/src/Whoops/Handler/Handler.php',
    'Whoops\\Handler\\HandlerInterface' => $vendorDir . '/filp/whoops/src/Whoops/Handler/HandlerInterface.php',
    'Whoops\\Handler\\JsonResponseHandler' => $vendorDir . '/filp/whoops/src/Whoops/Handler/JsonResponseHandler.php',
    'Whoops\\Handler\\PrettyPageHandler' => $vendorDir . '/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php',
    'Whoops\\Handler\\XmlResponseHandler' => $vendorDir . '/filp/whoops/src/Whoops/Handler/XmlResponseHandler.php',
    'Whoops\\Module' => $vendorDir . '/filp/whoops/src/Whoops/Provider/Zend/Module.php',
    'Whoops\\Provider\\Phalcon\\WhoopsServiceProvider' => $vendorDir . '/filp/whoops/src/Whoops/Provider/Phalcon/WhoopsServiceProvider.php',
    'Whoops\\Provider\\Silex\\WhoopsServiceProvider' => $vendorDir . '/filp/whoops/src/Whoops/Provider/Silex/WhoopsServiceProvider.php',
    'Whoops\\Provider\\Zend\\ExceptionStrategy' => $vendorDir . '/filp/whoops/src/Whoops/Provider/Zend/ExceptionStrategy.php',
    'Whoops\\Provider\\Zend\\RouteNotFoundStrategy' => $vendorDir . '/filp/whoops/src/Whoops/Provider/Zend/RouteNotFoundStrategy.php',
    'Whoops\\Run' => $vendorDir . '/filp/whoops/src/Whoops/Run.php',
);
```
In dev environment the generated autoload_classmap,php is working fine.
Removing  '../' in the production generated file fix the problem, but this is not intend to happen. 

I'm using Laravel 4.1 in my application, lastest version of composer, php 5.3, apache 2.2 in a Windows server (Xampp 1.7).

My composer.json (ommited some parts):
```json
{
	"require": {
		"laravel/framework": "4.1.*",
		"rhumsaa/array_column": "1.*",
		"patricktalmadge/bootstrapper": "dev-develop@dev"
	},
	"require-dev": {
		"barryvdh/laravel-ide-helper": "1.*",
		"barryvdh/laravel-debugbar" : "1.*",
		"orangehill/iseed": "dev-master@dev",
		"way/generators": "1.*",
		"barryvdh/laravel-migration-generator": "dev-master"
	},
	"autoload": {
		"classmap": [
			"/app/commands",
			"/app/controllers",
			"/app/models",
			"/app/database/migrations",
			"/app/database/seeds",
			"/app/tests/TestCase.php"
		],
		"psr-0": {
			"Pcm\\Indicators\\": "/src/"
		}
	}
}
```

### PR DESCRIPTION
**Pull request by gmsantosxl**
Resolves #3024

Passing the third argument as `true` on `findShortestPath ` method, a dummy file is added to `$from`. 
If `$from` ends with `/` (e.g. C:/ , /foo/bar/ ), a second `/` is inserted resulting on a invalid path.

### CODE REVIEW

**Comment by alcohol** [comment]
Please rename the function as it does not relate to the context. To check if you're dealing with a directory you would use http://php.net/is_dir. You are simply interested in knowing if the string ends with a `/` or not. That doesn't have anything to do with it actually being a directory.

The problem here is that after the `normalizePath()` call (which strips trailing `/` characters), root paths remain `/` (on *nix) and `<DRIVE>:/` (on windows). This then turns `$from` into `//dummy_file` on *nix and into `c://dummy_file` on windows. The function then correctly determines the path on *nix, but fails on windows. So the problem lies elsewhere in my humble opinion. Most likely due to on windows there being a prefix before the root `/`.

File: src/Composer/Util/Filesystem.php [hunk 1]
```diff
@@ -460,6 +460,17 @@ public static function isLocalPath($path)
...
         return (bool) preg_match('{^(file://|/|[a-z]:[\\\\/]|\.\.[\\\\/]|[a-z0-9_.-]+[\\\\/])}i', $path);
     }
+    
+    /**
+     * Return if the given path is a directory
+     *
+     * @param  string $path
+     * @return bool
+     */
+    public static function isDirectory($path)
```
Comment (stof) [inline src/Composer/Util/Filesystem.php]: why it is public ?

**Comment by alcohol** [comment]
On *nix the `$commonPath` ends up being `/` which then results in simply returning `$to` as shortest path. On Windows the `$commonPath` value is `c:/` which does not equal `/` so it continues processing and ends up with the leading `../`.

File: src/Composer/Util/Filesystem.php [hunk 2]
```diff
@@ -316,7 +316,7 @@ public function findShortestPath($from, $to, $directories = false)
         $to = lcfirst($this->normalizePath($to));
 
         if ($directories) {
-            $from .= '/dummy_file';
+            $from .= $this->isDirectory($from) ? 'dummy_file' : '/dummy_file';
```
Comment (alcohol) [inline src/Composer/Util/Filesystem.php]: I would personally just change this line to the following, no need for intermediate function

``` php
$from = rtrim($from, '/') . '/dummy_file';
```

File: src/Composer/Util/Filesystem.php (hunk 1 above)
Comment (Seldaek) [inline src/Composer/Util/Filesystem.php]: Yeah that should definitely be private or made to work with \ paths as well, because as is it depends on the path being normalized first.

File: src/Composer/Util/Filesystem.php (hunk 2 above)
Comment (alcohol) [inline src/Composer/Util/Filesystem.php]: At this point `$from` is normalized so you can't go wrong with this solution pretty much.

Comment (gmsantosxl) [inline src/Composer/Util/Filesystem.php]: Indeed, `rtrim($from, '/')` is enough

**Comment by Seldaek** [comment]
Thanks
