### PR TITLE
do not stumble over missing descriptions

### LINKED ISSUE #12151: Error when require a package with missing extension
My `composer.json`:

```json
{
    "require": {
        "php": ">=8.3",
        "symfony/messenger": "7.1.*"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking composer.lock: OK
Checking platform settings: OK
Checking git settings: OK git version 2.43.0
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking Composer version: OK
Checking Composer and its dependencies for vulnerabilities: OK
Composer version: 2.8.1
PHP version: 8.3.12
PHP binary path: /home/linuxbrew/.linuxbrew/Cellar/php/8.3.12/bin/php
OpenSSL version: OpenSSL 3.3.2 3 Sep 2024
curl version: 8.10.1 libz 1.3.1 ssl OpenSSL/3.3.2
zip: extension present, unzip present, 7-Zip not available
```

When I run this command (without the amqp required extension): 

```
composer require symfony/amqp-messenger
```

I get the following output: 

```
./composer.json has been updated
Running composer update symfony/amqp-messenger
Loading composer repositories with package information
Updating dependencies

In Problem.php line 652:

  [TypeError]
  substr(): Argument #1 ($string) must be of type string, null given


Exception trace:
  at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/DependencyResolver/Problem.php:652
 substr() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/DependencyResolver/Problem.php:652
 Composer\DependencyResolver\Problem::Composer\DependencyResolver\{closure}() at n/a:n/a
 array_map() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/DependencyResolver/Problem.php:651
 Composer\DependencyResolver\Problem::getProvidersList() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/DependencyResolver/Problem.php:281
 Composer\DependencyResolver\Problem::getMissingPackageReason() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/DependencyResolver/Rule.php:324
 Composer\DependencyResolver\Rule->getPrettyString() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/DependencyResolver/Problem.php:168
 Composer\DependencyResolver\Problem::formatDeduplicatedRules() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/DependencyResolver/Problem.php:111
 Composer\DependencyResolver\Problem->getPrettyString() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/DependencyResolver/SolverProblemsException.php:52
 Composer\DependencyResolver\SolverProblemsException->getPrettyString() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/Installer.php:513
 Composer\Installer->doUpdate() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/Installer.php:298
 Composer\Installer->run() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/Command/RequireCommand.php:498
 Composer\Command\RequireCommand->doUpdate() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/Command/RequireCommand.php:340
 Composer\Command\RequireCommand->execute() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/Console/Application.php:407
 Composer\Console\Application->doRun() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/src/Composer/Console/Application.php:147
 Composer\Console\Application->run() at phar:///home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer/bin/composer:93
 require() at /home/linuxbrew/.linuxbrew/Cellar/composer/2.8.1/bin/composer:29

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```

And I expected this to happen:

```
./composer.json has been updated
Running composer update symfony/amqp-messenger
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires symfony/amqp-messenger 7.1.* -> satisfiable by symfony/amqp-messenger[v7.1.0, v7.1.1].
    - symfony/amqp-messenger[v7.1.0, ..., v7.1.1] require ext-amqp * -> it is missing from your system. Install or enable PHP's amqp extension.

To enable extensions, verify that they are enabled in your .ini files:
    - /home/linuxbrew/.linuxbrew/etc/php/8.3/php.ini
    - /home/linuxbrew/.linuxbrew/etc/php/8.3/conf.d/20-igbinary.ini
    - /home/linuxbrew/.linuxbrew/etc/php/8.3/conf.d/20-msgpack.ini
    - /home/linuxbrew/.linuxbrew/etc/php/8.3/conf.d/20-redis.ini
    - /home/linuxbrew/.linuxbrew/etc/php/8.3/conf.d/20-xdebug.ini
    - /home/linuxbrew/.linuxbrew/etc/php/8.3/conf.d/ext-opcache.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-amqp` to temporarily ignore these required extensions.
```

### PR DESCRIPTION
**Pull request by xabbuh**
fixes #12151

### CODE REVIEW

File: src/Composer/Repository/ArrayRepository.php [hunk 1]
```diff
@@ -249,7 +249,7 @@ public function getProviders(string $packageName)
                 if ($packageName === $link->getTarget()) {
                     $result[$candidate->getName()] = [
                         'name' => $candidate->getName(),
-                        'description' => $candidate instanceof CompletePackageInterface ? $candidate->getDescription() : null,
+                        'description' => $candidate instanceof CompletePackageInterface ? $candidate->getDescription() : '',
```
Comment (stof) [inline src/Composer/Repository/ArrayRepository.php:252]: `getDescription()` still returns `?string` so this does not prevent having a `null` value. Instead, I suggest changing the documented return type of `ComposerRepository::getProviders()` to properly account for the fact that the description is nullable, and handling that in the caller.

**Comment by Seldaek** [comment]
Thanks

File: src/Composer/DependencyResolver/Problem.php [hunk 2]
```diff
@@ -649,7 +649,7 @@ private static function getProvidersList(RepositorySet $repositorySet, string $p
         $providers = $repositorySet->getProviders($packageName);
         if (\count($providers) > 0) {
             $providersStr = implode(array_map(static function ($p): string {
-                $description = $p['description'] !== '' ? ' '.substr($p['description'], 0, 100) : '';
+                $description = $p['description'] !== '' ? ' '.substr($p['description'] ?? '', 0, 100) : '';
```
Comment (stof) [inline src/Composer/DependencyResolver/Problem.php:652]: the condition in the left of the ternary should probably be `$p['description'] !== '' && $p['description'] !== null` instead, to avoid adding a space for packages without description at all.

**Comment by BazylPL** [comment]
When is it going to be released?

**Comment by Whip** [comment]
When will this change be available for update? Is there a temporary solution to make it work?

**Comment by Seldaek** [comment]
`composer self-update --snapshot` gets you the latest build which has the fix.
