### PR TITLE
Fix error when vendor dir contains broken symlinks

### LINKED ISSUE #11668: Error Unhandled promise rejection with DirectoryNotFoundException
This error occurs when a vendor dir contains a symlink to a non-existing path.
STR
1) Create two composer.json files with names: `dev.json`, `composer.json`

a) dev.json
```json
{
    "repositories": [
        {
            "type": "path",
            "url": "../libs/*"
        }
    ],
    "require": {
        "vnd/pkg": "*"
    }
}
```

b) composer.json
```json
{
    "require": {
        "vnd/pkg": "*"
    }
}
```
2) Run commands

```
composer install
COMPOSER=dev.json composer install
```

3) Remove directory `../libs/path_to_pkg_lib` or make `git checkout branch-name` where  path_to_pkg_lib does not exists 

4) Run command `composer install` 

**Actual result**

```
    Install of symfony/http-client failed
Unhandled promise rejection with Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "vendor/composer/3b81563b" directory does not exist. in phar:///usr/local/bin/composer/vendor/symfony/finder/Finder.php:592
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Downloader/ArchiveDownloader.php(126): Symfony\Component\Finder\Finder->in()
#1 phar:///usr/local/bin/composer/src/Composer/Downloader/ArchiveDownloader.php(172): Composer\Downloader\ArchiveDownloader::Composer\Downloader\{closure}()
#2 phar:///usr/local/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php(47): Composer\Downloader\ArchiveDownloader->Composer\Downloader\{closure}()
#3 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(169): React\Promise\Internal\FulfilledPromise->then()
#4 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(217): React\Promise\Promise::React\Promise\{closure}()
#5 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(279): React\Promise\Promise->settle()
#6 phar:///usr/local/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php(47): React\Promise\Promise::React\Promise\{closure}()
#7 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(176): React\Promise\Internal\FulfilledPromise->then()
#8 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(217): React\Promise\Promise::React\Promise\{closure}()
#9 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(279): React\Promise\Promise->settle()
#10 phar:///usr/local/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php(47): React\Promise\Promise::React\Promise\{closure}()
#11 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(176): React\Promise\Internal\FulfilledPromise->then()
#12 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(217): React\Promise\Promise::React\Promise\{closure}()
#13 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(279): React\Promise\Promise->settle()
#14 [internal function]: React\Promise\Promise::React\Promise\{closure}()
#15 phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php(328): call_user_func()
#16 phar:///usr/local/bin/composer/src/Composer/Util/Loop.php(90): Composer\Util\ProcessExecutor->countActiveJobs()
#17 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(667): Composer\Util\Loop->wait()
#18 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(221): Composer\Installer\InstallationManager->runCleanup()
#19 phar:///usr/local/bin/composer/src/Composer/Installer.php(803): Composer\Installer\InstallationManager->execute()
#20 phar:///usr/local/bin/composer/src/Composer/Installer.php(292): Composer\Installer->doInstall()
#21 phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php(147): Composer\Installer->run()
#22 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(298): Composer\Command\InstallCommand->execute()
#23 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#24 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#25 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(382): Symfony\Component\Console\Application->doRun()
#26 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#27 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(145): Symfony\Component\Console\Application->run()
#28 phar:///usr/local/bin/composer/bin/composer(93): Composer\Console\Application->run()
#29 /usr/local/bin/composer(29): require('...')
#30 {main}

.... more errors  ... 

    Install of symfony/lock failed
Unhandled promise rejection with RuntimeException: Failed to extract symfony/lock as the installation was aborted by another package operation. in phar:///usr/local/bin/composer/src/Composer/Downloader/ZipDownloader.php:179
Stack trace:
#0 phar:///usr/local/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php(47): Composer\Downloader\ZipDownloader->Composer\Downloader\{closure}()
#1 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(169): React\Promise\Internal\FulfilledPromise->then()
#2 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(217): React\Promise\Promise::React\Promise\{closure}()
#3 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(279): React\Promise\Promise->settle()
#4 phar:///usr/local/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php(47): React\Promise\Promise::React\Promise\{closure}()
#5 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(176): React\Promise\Internal\FulfilledPromise->then()
#6 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(217): React\Promise\Promise::React\Promise\{closure}()
#7 phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php(279): React\Promise\Promise->settle()
#8 [internal function]: React\Promise\Promise::React\Promise\{closure}()
#9 phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php(328): call_user_func()
#10 phar:///usr/local/bin/composer/src/Composer/Util/Loop.php(90): Composer\Util\ProcessExecutor->countActiveJobs()
#11 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(667): Composer\Util\Loop->wait()
#12 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(221): Composer\Installer\InstallationManager->runCleanup()
#13 phar:///usr/local/bin/composer/src/Composer/Installer.php(803): Composer\Installer\InstallationManager->execute()
#14 phar:///usr/local/bin/composer/src/Composer/Installer.php(292): Composer\Installer->doInstall()
#15 phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php(147): Composer\Installer->run()
#16 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(298): Composer\Command\InstallCommand->execute()
#17 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#18 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#19 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(382): Symfony\Component\Console\Application->doRun()
#20 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(171): Composer\Console\Application->doRun()
#21 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(145): Symfony\Component\Console\Application->run()
#22 phar:///usr/local/bin/composer/bin/composer(93): Composer\Console\Application->run()
#23 /usr/local/bin/composer(29): require('...')
#24 {main}

```

**expected result**
there shouldn't be an error

If remove broken symlink it works fine again. `rm vendor/symfony/proxy-manager-bridge`
Selection_1739

### PR DESCRIPTION
**Pull request by vtsykun**
Fixes #11668

### CODE REVIEW

**Comment by Rodrigostrong** [comment]
> Fixes #11668 
> 
> 

Não

**Review by Rodrigostrong — CHANGES_REQUESTED** [review]
Eu

File: src/Composer/Util/Filesystem.php [hunk 1]
```diff
@@ -251,6 +251,9 @@ public function ensureDirectoryExists(string $directory)
                     $directory.' exists and is not a directory.'
                 );
             }
+            if (is_link($directory)) {
+                @$this->unlinkImplementation($directory);
```
Comment (nvdbeek) [inline src/Composer/Util/Filesystem.php:255]: When the unlink gives something wrong you never see this, otherwise there is no reason to 'supress' the termination cause the link is always exists (is_link)?

Comment (vtsykun) [reply src/Composer/Util/Filesystem.php]: you are right, I added an error message when the symbolic link could not be deleted. But at the same time I'd like to make minimal changes to current logic, so I added supress on unlink

File: src/Composer/Util/Filesystem.php [hunk 2]
```diff
@@ -251,10 +251,15 @@ public function ensureDirectoryExists(string $directory)
...
-                throw new \RuntimeException(
-                    $directory.' does not exist and could not be created.'
-                );
+
+            $error = null;
+            if (is_link($directory) && !@$this->unlinkImplementation($directory)) {
+                $error = 'Could not delete symbolic link '.$directory.': '.(error_get_last()['message'] ?? '');
+            }
+
+            $error = @mkdir($directory, 0777, true) ? null : ($error ?? $directory.' does not exist and could not be created: '.(error_get_last()['message'] ?? ''));
```
Comment (stof) [inline src/Composer/Util/Filesystem.php:260]: please use a `if/else` rather than a ternary here. Currently, your `@` suppresses errors for the whole ternary, which is not what we want here as it could hide issues in the composer code.

File: src/Composer/Util/Filesystem.php [hunk 3]
```diff
@@ -251,10 +251,15 @@ public function ensureDirectoryExists(string $directory)
...
                 );
             }
-            if (!@mkdir($directory, 0777, true)) {
-                throw new \RuntimeException(
-                    $directory.' does not exist and could not be created.'
-                );
+
+            $error = null;
+            if (is_link($directory) && !@$this->unlinkImplementation($directory)) {
+                $error = 'Could not delete symbolic link '.$directory.': '.(error_get_last()['message'] ?? '');
```
Comment (stof) [inline src/Composer/Util/Filesystem.php:257]: Why not throwing the RuntimeException here instead of attempting to create the directory but remembering the previous error ?

Comment (vtsykun) [reply src/Composer/Util/Filesystem.php:257]: I didn't want to add a new point where an exception could be thrown, (i.e if unlink == false OR mkdir == false). Unlink made fails on Windows by may reasons, like antivirus, FS locking, so I throw an exception like before only on `mkdir = false`. But I can change that if it's safe
