### PR TITLE
fixes #8179

### LINKED ISSUE #8179: HgDriver on php5.3 Fatal error: Using $this when not in object context
We are in the process to upgrade our 5.3 codebase to 7.2, but we've hit a snag when working with composer: it simply errors out on php5.3when trying to initialize the hg driver. This code is using $this in an anonymous function, which is not allowed in php5.3.

Offending code:

```
                $command = function ($url) {
                    return sprintf('hg clone --noupdate %s %s', ProcessExecutor::escape($url), ProcessExecutor::escape($this->repoDir));
                };

                $hgUtils->runCommand($command, $this->url, $this->repoDir);
```

My `composer.json`:

```json
Imagine a link to a hg repo in here
```

Output of `composer diagnose`:

```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.doctrine/cache : exact version constraints (1.5.4) should be avoided if the package follows semantic versioning
Checking platform settings: The xdebug extension is loaded, this can slow down Composer a little.
 Disabling it when using Composer is recommended.

Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.5
PHP version: 5.3.10
```

When I run this command:

```
php composer.phar update

```

I get the following output:

```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
[11-Jun-2019 10:28:07 UTC] PHP Fatal error:  Using $this when not in object context in phar:///src/idefix/application/composer.phar/src/Composer/Repository/Vcs/HgDriver.php on line 65

Fatal error: Using $this when not in object context in phar:///src/idefix/application/composer.phar/src/Composer/Repository/Vcs/HgDriver.php on line 65
```

And I expected this to happen:

It to work. ;) As far as I know Composer works with 5.3.  There is another issue with the same error #251, but it references a different problem.

### PR DESCRIPTION
**Pull request by alcohol**

### CODE REVIEW

File: src/Composer/Repository/Vcs/HgDriver.php [hunk 1]
```diff
@@ -61,8 +61,9 @@ public function initialize()
                 // clean up directory and do a fresh clone into it
                 $fs->removeDirectory($this->repoDir);
 
-                $command = function ($url) {
-                    return sprintf('hg clone --noupdate %s %s', ProcessExecutor::escape($url), ProcessExecutor::escape($this->repoDir));
+                $self = $this;
+                $command = function ($url) use ($self) {
+                    return sprintf('hg clone --noupdate %s %s', ProcessExecutor::escape($url), ProcessExecutor::escape($self->repoDir));
```
Comment (Seldaek) [inline src/Composer/Repository/Vcs/HgDriver.php]: $repoDir property needs to be made public for this to work, or probably better solution is to assign $repoDir = $this->repoDir and `use` that instead of `$self`.

**Comment by Seldaek** [comment]
Hm, somehow didn't get an email for the force push it seems..

**Comment by alcohol** [comment]
I think you get a notification though when I marked the issue as resolved? :man_shrugging: I figured since that was the only feedback and everything else was in order, it wouldn't hurt to merge it :d

**Comment by Seldaek** [comment]
Nope marking resolved doesn't notify either (by mail at least). Anyway totally fine to merge yes was just surprised I did not see this before.
