### PR TITLE
Fix output listing some updates that do not really happen when updating mirrors/--lock

### LINKED ISSUE #9812: composer update --lock also SEEMS to update dev packages, but doesn't really
My `composer.json`: full of secrets, sorry, but the important part:

```
{
    "require": {
        "php": ">=7.4",
        "cweagans/composer-patches": "^1.6",
        "kris/laravel-form-builder": "dev-master"
    },
    "extra": {
        "patches": {
            // nothing for kris/laravel-form-builder
        }
    }
}
```

I include `cweagans/composer-patches` because it might be relevant as a composer plugin, even though there are no patches for `kris/laravel-form-builder`.

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.12
PHP version: 7.4.15
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1j  16 Feb 2021
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1j
zip: extension present, unzip present
```

Full output of `update --lock`:

```
rudie@homeblox:myproject(dev)$ composer -vvv update --lock
Reading ./composer.json (/var/www/myproject/composer.json)
Loading config file /home/rudie/.config/composer/auth.json
Loading config file ./composer.json (/var/www/myproject/composer.json)
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/var/www/myproject): git branch -a --no-color --no-abbrev -v
Reading /home/rudie/.config/composer/composer.json
Loading config file /home/rudie/.config/composer/auth.json
Loading config file /home/rudie/.config/composer/composer.json (/home/rudie/.config/composer/composer.json)
Loading config file /home/rudie/.config/composer/auth.json
Reading /home/rudie/.config/composer/auth.json
Reading /var/www/myproject/vendor/composer/installed.json
Reading /home/rudie/.config/composer/vendor/composer/installed.json
Loading plugin cweagans\Composer\Patches (from cweagans/composer-patches)
Running 2.0.12 (2021-04-01 10:14:59) with PHP 7.4.15 on Linux / 4.15.0-140-generic
> pre-update-cmd: cweagans\Composer\Patches->checkPatches
Gathering patches for root package.
Reading ./composer.lock (/var/www/myproject/composer.lock)
Loading composer repositories with package information
Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing /home/rudie/.cache/composer/repo/https---repo.packagist.org/packages.json into cache
Reading /home/rudie/.cache/composer/repo/https---repo.packagist.org/provider-brick~math.json from cache
Downloading https://repo.packagist.org/p2/brick/math.json if modified
....
[304] https://repo.packagist.org/p2/brick/math.json
....
Downloading https://repo.packagist.org/p2/guzzlehttp/psr7.json if modified
....
Reading /home/rudie/.cache/composer/repo/https---repo.packagist.org/provider-illuminate~mail.json from cache
Downloading https://repo.packagist.org/p2/illuminate/mail.json if modified
....
[304] https://repo.packagist.org/p2/illuminate/bus.json
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.038 seconds
Analyzed 4689 packages to resolve dependencies
Analyzed 31374 rules to resolve dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.001 seconds
Lock file operations: 0 installs, 1 update, 0 removals
Updates: kris/laravel-form-builder:dev-master cd17545
  - Upgrading kris/laravel-form-builder (dev-master 538ed8d => dev-master cd17545)
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
> post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAutoloadDump
54 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

The weird bit in there is:

```
Lock file operations: 0 installs, 1 update, 0 removals
Updates: kris/laravel-form-builder:dev-master cd17545
  - Upgrading kris/laravel-form-builder (dev-master 538ed8d => dev-master cd17545)
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
```

So it pretends to upgrade `kris/laravel-form-builder` to the newest dev, even though `--lock` shouldn't do that, but also it actually doesn't. If I run the same command again, it pretends to upgrade again, and again, etc, and it never does upgrade. Very very confusing.

Happened in Composer 2.0.11, so I upgraded to 2.0.12, and it still happens.

### PR DESCRIPTION
**Pull request by Seldaek**
Fixes #9812

Note that without the fix, the test I changed would have an output of:

```
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 5 updates, 0 removals
  - Upgrading a/a (dev-master 1111111 => dev-master 2222222)
  - Upgrading b/b (2.0.3 1111111 => 2.0.3 2222222)
  - Upgrading c/c (1.0.0 1111111 => 1.0.0 2222222)
  - Upgrading f/f (dev-master 1111111 => dev-master 2222222)
  - Upgrading g/g (dev-master 0000000 => dev-master 1111111)
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
```

The issue is we do output the update operations which do happen but then in LockTransaction::getNewLockPackages those changes are internally reverted by restoring the old references in the packages written to the lock file.

Possibly related to https://github.com/composer/composer/issues/8827 for a more proper fix later.

### CODE REVIEW

**Comment by naderman** [comment]
Not sure I follow? Why are there update operations at all if they get reverted?

File: src/Composer/Installer.php [hunk 1]
```diff
@@ -446,6 +446,15 @@ protected function doUpdate(InstalledRepositoryInterface $localRepo, $doInstall)
                     $installsUpdates[] = $operation;
                     $installNames[] = $operation->getPackage()->getPrettyName().':'.$operation->getPackage()->getFullPrettyVersion();
                 } elseif ($operation instanceof UpdateOperation) {
+                    // when mirrors/metadata from a package gets updated we do not want to list it as an
+                    // update in the output as it is only an internal lock file metadata update
+                    if ($this->updateMirrors
+                        && $operation->getInitialPackage()->getName() == $operation->getTargetPackage()->getName()
+                        && $operation->getInitialPackage()->getVersion() == $operation->getTargetPackage()->getVersion()
```
Comment (naderman) [inline src/Composer/Installer.php:453]: I disagree, I think if you do update mirrors and references change this should be output?

**Comment by Seldaek** [comment]
This is for `update mirrors` or `update --lock`, so the references do not change. See https://github.com/composer/composer/blob/101a5e2a21c68f53015361afde5da1d812615457/src/Composer/DependencyResolver/LockTransaction.php#L96-L102

The update ops are there to sync up the rest of the metadata and make sure the latest URLs/mirrors/.. are updated in the lock file. But the packages do not actually update so I don't think we should show an update, and especially we should not show updates to a new reference if the reference is not changing in the lock file.

**Comment by naderman** [comment]
Oh I see, would be great to see metadata diff one day but okay, makes sense now ;-)

**Review by naderman — APPROVED** [review]

**Review by naderman — APPROVED** [review]

File: src/Composer/Installer.php [hunk 2]
```diff
@@ -446,6 +446,15 @@ protected function doUpdate(InstalledRepositoryInterface $localRepo, $doInstall)
                     $installsUpdates[] = $operation;
                     $installNames[] = $operation->getPackage()->getPrettyName().':'.$operation->getPackage()->getFullPrettyVersion();
                 } elseif ($operation instanceof UpdateOperation) {
+                    // when mirrors/metadata from a package gets updated we do not want to list it as an
+                    // update in the output as it is only an internal lock file metadata update
+                    if ($this->updateMirrors
```
Comment (stof) [inline src/Composer/Installer.php:451]: I think this `$this->updateMirrors` check is the wrong one. An update of the URL wtihout updating the reference could also happen in case of partial updates IIRC.

Comment (naderman) [reply src/Composer/Installer.php:451]: In case of a partial update however the lock file doesn't later get reset to the old revision, so outputting this would be fine.

Comment (stof) [reply src/Composer/Installer.php:451]: so if you do a partial update, we don't update mirror urls of the locked packages ?

Comment (naderman) [reply src/Composer/Installer.php:451]: Sure we do, but there is no need to hide the update operation there?

Comment (Seldaek) [reply src/Composer/Installer.php:451]: Well no in that case we don't do it for packages which are locked, only for the packages which are updated. 

Only composer update mirrors (or --lock which is an alias) does that for all packages and nothing else. Doing it for all partial updates would slow things down quite a bit for little added benefit.

Comment (naderman) [reply src/Composer/Installer.php:451]: Sorry I thought he meant locked packages which are being updated as part of the partial update :D EIther way it's fine as is here ;-)
