### PR TITLE
fix #4936: warn user about auth overwriting

### LINKED ISSUE #4936: HTTP Basic Auth collides with Gitlab OAuth Token authentication
This might not be a problem a lot of people will hit but should be fixed to avoid confusion. Background: We recently migrated from a pure git+https setup to Gitlab. During that migration I wanted to let Satis use the GitlabDriver to improve the overall performance.

In my auth.json file I had the old HTTP Basic Auth credentials for the gitlab host (because we did not change the hostname during the migration) which after the migration did not work any more. on the first run Composer was able to ask me for the Gitlab OAuth Token and add it to the global auth.json file without a problem. But when running Composer a second time the Gitlab OAuth Token was not recognized and Composer asked me again for the Gitlab credentials.

When removing the HTTP Basic Auth credentials Composer is running fine. I was not yet able to debug the issue in the code, so I am not sure if this is a general problem or *just* an issue with the GitlabDriver.

### PR DESCRIPTION
**Pull request by e-moe**

### CODE REVIEW

File: src/Composer/IO/BaseIO.php [hunk 1]
```diff
@@ -52,6 +52,14 @@ public function getAuthentication($repositoryName)
...
     public function setAuthentication($repositoryName, $username, $password = null)
     {
+        if ($this->hasAuthentication($repositoryName)) {
+            $this->writeError(
+                sprintf(
+                    "<warning>Warning: You should avoid overwriting already defined auth settings for %s.</warning>",
+                    $repositoryName
+                )
+            );
+        }
```
Comment (Seldaek) [inline src/Composer/IO/BaseIO.php]: Sorry but this really has to be checked in loadConfiguration below before calling setAuthentication, because otherwise when we do interactive prompts for passwords we might end up writing the same auth domain/repositoryName a few times and I think that'd be quite confusing for users to see this warning at that point.

Comment (e-moe) [inline src/Composer/IO/BaseIO.php]: @Seldaek, thanks for review! I will update my pull request.
what do you think if I'll replace `setAuthentication` call inside `loadConfiguration` to new protected function with this check/warning inside?

Comment (e-moe) [inline src/Composer/IO/BaseIO.php]: please, review updated code

**Comment by Seldaek** [comment]
Looks good like this I think, thanks :)

**Comment by renatomefidf** [comment]
Guys, I think its bugged, from nothing my composer started yelling this error all the time. I only have one auth.json config file and no domains repetitions, it also yells errors even when in an empty directory I do a composer require some package.
Somehow seems like the auth.json is getting read twice!

How can I better try to debug this to help?

**Comment by eXistenZNL** [comment]
+1, I am experiencing the same. To reproduce, just go to a random directory and type

`composer require symfony/console`

In my case I see two warnings because I have both authentication for GitHub and GitLab:

```
Using version ^3.0 for symfony/console
./composer.json has been updated
Warning: You should avoid overwriting already defined auth settings for github.com.
Warning: You should avoid overwriting already defined auth settings for gitlab.com.
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

Please fix as the yellow warning is quite annoying :)

**Comment by Seldaek** [comment]
Hmm.. could be due to loading the global auth file.. I'll investigate.

**Comment by Seldaek** [comment]
In the meantime if either of you could paste the content of their auth.json (both global and local if present) without passwords obviously but just wondering how the config looks like.. And also please check if you have in composer.json or global config.json some auth config as well.

**Comment by Seldaek** [comment]
Can't reproduce this here guys so I need one of you to give more details.

**Comment by eXistenZNL** [comment]
Thx for the quick response! My auth.json is as follows:

``` 
{
    "github-oauth": {
        "github.com": "12345"
    },
    "gitlab-oauth": {
        "gitlab.com": "12345"
    }
}
```

and my config.json is this:

```
{
    "config": {
    }
}
```

**Comment by Seldaek** [comment]
@eXistenZNL no warning for me using that.. Can you paste the output of `composer require -vvv symfony/console`? At least the part until the warnings.

**Comment by Seldaek** [comment]
@eXistenZNL @renatomefidf please giv eme full -vvv output :)

**Comment by renatomefidf** [comment]
verbose output:
```
Changed CWD to /home/renatomefi/Workspace/PHP/testbla
Reading ./composer.json
Loading config file /home/renatomefi/.composer/config.json
Loading config file /home/renatomefi/.composer/auth.json
Loading config file ./composer.json
Checking CA file /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
Executing command (/home/renatomefi/Workspace/PHP/testbla): git branch --no-color --no-abbrev -v
Executing command (/home/renatomefi/Workspace/PHP/testbla): git describe --exact-match --tags
Failed to initialize global composer: Composer could not find the config file: /home/renatomefi/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /home/renatomefi/Workspace/PHP/testbla/vendor/composer/installed.json
Downloading https://packagist.org/packages.json
Writing /home/renatomefi/.composer/cache/repo/https---packagist.org/packages.json into cache
Downloading http://packagist.org/p/provider-2013%246965b2932c5ab77fc051df30b62c3bb5657962b4529feb48b763577753c9f1ee.json
Writing /home/renatomefi/.composer/cache/repo/https---packagist.org/p-provider-2013.json into cache
Downloading http://packagist.org/p/provider-2014%24fc8a514e0ededf5b65b648318ecd295d8d58965663de4bc552dd5009c5afde8b.json
Writing /home/renatomefi/.composer/cache/repo/https---packagist.org/p-provider-2014.json into cache
Downloading http://packagist.org/p/provider-2015%2443485cd1b81211238ad0436cbf46988695b464e33f344cd8e8a459c536788086.json
Writing /home/renatomefi/.composer/cache/repo/https---packagist.org/p-provider-2015.json into cache
Downloading http://packagist.org/p/provider-2015-04%24db94e31deda860c2edb50715674b7034013de51d068bea8ba02247ff580d0580.json
Writing /home/renatomefi/.composer/cache/repo/https---packagist.org/p-provider-2015-04.json into cache
Downloading http://packagist.org/p/provider-2015-07%24de181915818233629bfd6db2db8a1dd519294b89c128d51012236498f00f051f.json
Writing /home/renatomefi/.composer/cache/repo/https---packagist.org/p-provider-2015-07.json into cache
Downloading http://packagist.org/p/provider-2015-10%242142fc835db8c18162c3033074779738bb5dac841ec5cf0ce6f0fdc62ba987cf.json
Writing /home/renatomefi/.composer/cache/repo/https---packagist.org/p-provider-2015-10.json into cache
Downloading http://packagist.org/p/provider-2016-01%2441a8929151294b66eaf7154bed8f3f7e56ea5cbcffae46f4e602c69c401e43cd.json
Writing /home/renatomefi/.composer/cache/repo/https---packagist.org/p-provider-2016-01.json into cache
Reading /home/renatomefi/.composer/cache/repo/https---packagist.org/p-provider-archived.json from cache
Downloading http://packagist.org/p/provider-latest%242792bb810759ae0719928d04f310a7ba4a85886fed17865c5c347edcf3009a47.json
Writing /home/renatomefi/.composer/cache/repo/https---packagist.org/p-provider-latest.json into cache
Downloading http://packagist.org/p/symfony/console%24b9b633949e9eefc04428a610fd5d4d5fbee339a61da7aea55e677c88e2d49bf2.json
Writing /home/renatomefi/.composer/cache/repo/https---packagist.org/provider-symfony$console.json into cache
Using version ^3.0 for symfony/console
./composer.json has been updated
Reading ./composer.json
Loading config file /home/renatomefi/.composer/config.json
Loading config file /home/renatomefi/.composer/auth.json
Loading config file ./composer.json
Warning: You should avoid overwriting already defined auth settings for github.com.
Executing command (/home/renatomefi/Workspace/PHP/testbla): git branch --no-color --no-abbrev -v
Executing command (/home/renatomefi/Workspace/PHP/testbla): git describe --exact-match --tags
Failed to initialize global composer: Composer could not find the config file: /home/renatomefi/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /home/renatomefi/Workspace/PHP/testbla/vendor/composer/installed.json
Reading ./composer.lock
```
home config.json
```
{
    "config": {
    }
}
```

home auth.json
```
{
    "github-oauth": {
        "github.com": "key"
    }
}
```

./composer.json
```
{
    "require": {
        "symfony/console": "^3.0"
    }
}
```

**Comment by curry684** [comment]
```
./composer.json has been updated
Reading ./composer.json
```
It's caused by the reload when `composer.json` was updated.

**Comment by Seldaek** [comment]
Fixed in https://github.com/composer/composer/commit/6d1e8ebf90542a7c65ac6661f6c47b1d655641d9

**Comment by renatomefidf** [comment]
Cool, that was pretty fast! :)

Thanks

**Comment by eXistenZNL** [comment]
Confirmed to be working both on my native host and my docker image.

I found this whilst trying to build the [fastest smallest composer docker image possible](https://hub.docker.com/r/existenz/composer/), so at first I thought I missed a dependency or an extension or so but then I also noticed the same problem when running on my host.

Just checked and the problem is gone in both my docker image (Based on Alpine Linux), and my host (Ubuntu 15.10)

Thanks!
