### PR TITLE
fixes #3974: Autoloader have to distinguish between files and directories

### LINKED ISSUE #3974: Autoloader have to distinguish between files and directories
The autoloader only checks for file existence using `file_exists` but not if it's really a file.

Example:
========

`/psr0/Namespace/Dir.php`  <-- This is a file containing class `Namespace\Dir`
`/psr4/Dir.php`  <-- This is a directory

composer.json:
------------
```json
    "autoload": {
        "psr-0": {
            "Namespace\\": "psr0/"
        },
        "psr-4": {
            "Namespace\\": "psr4/"
        }
    }
```

index.php:
--------------
```php
require_once __DIR__ . '/vendor/autoload.php';
var_dump(new Namespace\Dir());
```

Result:
------------
```
PHP Warning:  include(.../psr4/Dir.php): failed to open stream: Inappropriate ioctl for device in .../vendor/composer/ClassLoader.php on line 412
PHP Stack trace:
PHP   1. {main}() .../index.php:0
PHP   2. spl_autoload_call() .../index.php:5
PHP   3. Composer\Autoload\ClassLoader->loadClass() .../index.php:0
PHP   4. Composer\Autoload\includeFile() .../vendor/composer/ClassLoader.php:301
PHP Warning:  include(): Failed opening '.../psr4/Dir.php' for inclusion (include_path='...') in .../vendor/composer/ClassLoader.php on line 412
PHP Stack trace:
PHP   1. {main}() .../index.php:0
PHP   2. spl_autoload_call() .../index.php:5
PHP   3. Composer\Autoload\ClassLoader->loadClass() .../index.php:0
PHP   4. Composer\Autoload\includeFile().../vendor/composer/ClassLoader.php:301
PHP Fatal error:  Class 'Namespace\Dir' not found in .../index.php on line 5
PHP Stack trace:
PHP   1. {main}() .../index.php:0
```

Expected:
------------
```
class Namespace\Dir#2 (0) {
}
```

### PR DESCRIPTION
**Pull request by marc-mabe**
#3974

### CODE REVIEW

File: tests/Composer/Test/Autoload/ClassLoaderTest.php [hunk 1]
```diff
@@ -9,6 +9,17 @@
  */
 class ClassLoaderTest extends \PHPUnit_Framework_TestCase
 {
+    public function testLoadClassDotPhp()
+    {
+        $loader = new ClassLoader();
+        $loader->add('DirDotPhp\\', __DIR__ . '/Fixtures');
+        $loader->addPsr4('DirDotPhp\\', __DIR__ . '/Fixtures/DirDotPhp/psr4');
+
+	$class = 'DirDotPhp\\Dir';
```
Comment (alcohol) [inline tests/Composer/Test/Autoload/ClassLoaderTest.php]: Indentation.

Comment (marc-mabe) [inline tests/Composer/Test/Autoload/ClassLoaderTest.php]: fixed

**Comment by Seldaek** [comment]
Merging as it's strictly correct and should be harmless but I'd argue the use case is a bit far fetched :)
