### PR TITLE
Rewrote DependsCommand

### LINKED ISSUE #4911: Depends incorrectly handles dev dependencies
`composer depends` command should only consider `require-dev` dependencies from the root package, but it doesn't:
```
$ cat composer.json
{
    "require": {
        "symfony/symfony": "^3.0",
        "doctrine/orm": "^2.5"
    },
    "require-dev": {
        "phpunit/phpunit": "^5.2"
    }
}
$ composer depends phpunit/phpunit
__root__ requires (dev) phpunit/phpunit (^5.2)
doctrine/annotations requires (dev) phpunit/phpunit (4.*)
doctrine/cache requires (dev) phpunit/phpunit (~4.8|~5.0)
doctrine/collections requires (dev) phpunit/phpunit (~4.0)
doctrine/common requires (dev) phpunit/phpunit (~4.8|~5.0)
doctrine/dbal requires (dev) phpunit/phpunit (4.*)
doctrine/inflector requires (dev) phpunit/phpunit (4.*)
doctrine/instantiator requires (dev) phpunit/phpunit (~4.0)
doctrine/orm requires (dev) phpunit/phpunit (~4.0)
myclabs/deep-copy requires (dev) phpunit/phpunit (~4.1)
paragonie/random_compat requires (dev) phpunit/phpunit (4.*|5.*)
phpdocumentor/reflection-docblock requires (dev) phpunit/phpunit (~4.0)
phpunit/php-code-coverage requires (dev) phpunit/phpunit (~5)
phpunit/php-token-stream requires (dev) phpunit/phpunit (~4.2)
phpunit/phpunit-mock-objects requires (dev) phpunit/phpunit (~5)
sebastian/comparator requires (dev) phpunit/phpunit (~4.4)
sebastian/diff requires (dev) phpunit/phpunit (~4.8)
sebastian/environment requires (dev) phpunit/phpunit (~4.4)
sebastian/exporter requires (dev) phpunit/phpunit (~4.4)
sebastian/global-state requires (dev) phpunit/phpunit (~4.2)
sebastian/recursion-context requires (dev) phpunit/phpunit (~4.4)
```
It should only output the first line of course.

I'm in the process of rewriting the entire DependsCommand, but logging a separate issue for this bug in the current version in case I don't get that done for some reason.

### PR DESCRIPTION
**Pull request by curry684**
Rewrote `composer depends` completely.

- Dropped `--link-type` parameter as it implied wrong logic, fixes #4911 
- Dropped `--with-replaces` parameter as it caused [nonsensical indirect hits](https://github.com/composer/composer/issues/4911#issuecomment-183966204). Direct replaces are always shown though
- Added `--recursive` parameter to recursively find up to the root why a package is present
- Added `--tree` to render recursive output in a nice tree without undubbing

Options `-i` and `-m` were preserved.

Sample output:
```
$ composer depends doctrine/lexer
 doctrine/annotations v1.2.7 requires doctrine/lexer (1.*)
 doctrine/common      v2.6.1 requires doctrine/lexer (1.*)

$ composer depends doctrine/lexer -r
 __root__             -      requires doctrine/orm (^2.5)
 doctrine/orm         v2.5.4 requires doctrine/dbal (>=2.5-dev,<2.6-dev)
 __root__             -      requires symfony/symfony (^3.0)
 doctrine/common      v2.6.1 requires doctrine/annotations (1.*)
 doctrine/dbal        v2.5.4 requires doctrine/common (>=2.4,<2.7-dev)
 doctrine/orm         v2.5.4 requires doctrine/common (>=2.5-dev,<2.7-dev)
 symfony/symfony      v3.0.2 requires doctrine/common (~2.4)
 doctrine/annotations v1.2.7 requires doctrine/lexer (1.*)
 doctrine/common      v2.6.1 requires doctrine/lexer (1.*)

$ composer depends doctrine/lexer -t
doctrine/lexer v1.0.1 Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
|- doctrine/annotations v1.2.7 (requires doctrine/lexer 1.*)
|  `- doctrine/common v2.6.1 (requires doctrine/annotations 1.*)
|     |- doctrine/dbal v2.5.4 (requires doctrine/common >=2.4,<2.7-dev)
|     |  `- doctrine/orm v2.5.4 (requires doctrine/dbal >=2.5-dev,<2.6-dev)
|     |     `- __root__ (requires doctrine/orm ^2.5)
|     |- doctrine/orm v2.5.4 (requires doctrine/common >=2.5-dev,<2.7-dev)
|     |  `- __root__ (requires doctrine/orm ^2.5)
|     `- symfony/symfony v3.0.2 (requires doctrine/common ~2.4)
|        `- __root__ (requires symfony/symfony ^3.0)
`- doctrine/common v2.6.1 (requires doctrine/lexer 1.*)
   |- doctrine/dbal v2.5.4 (requires doctrine/common >=2.4,<2.7-dev)
   |  `- doctrine/orm v2.5.4 (requires doctrine/dbal >=2.5-dev,<2.6-dev)
   |     `- __root__ (requires doctrine/orm ^2.5)
   |- doctrine/orm v2.5.4 (requires doctrine/common >=2.5-dev,<2.7-dev)
   |  `- __root__ (requires doctrine/orm ^2.5)
   `- symfony/symfony v3.0.2 (requires doctrine/common ~2.4)
      `- __root__ (requires symfony/symfony ^3.0)
```
BC parameters:
```
$ composer depends symfony/symfony -m ^4.0
There is no installed package depending on "symfony/symfony" in versions matching 4.0

$ composer depends symfony/symfony -m ^3.9
 __root__ - requires symfony/symfony (^3.0)

$ composer depends symfony/symfony -im ^3.9
There is no installed package depending on "symfony/symfony" in versions not matching 3.9

$ composer depends symfony/symfony -im ^2.7
 __root__ - requires symfony/symfony (^3.0)
```
Tests for #4911 and the new `replace` detection:
```
$ composer depends phpunit/phpunit
 __root__ - requires (for development) phpunit/phpunit (^5.2)

$ composer depends symfony/yaml
 phpunit/phpunit 5.2.4  requires symfony/yaml (~2.1|~3.0)
 symfony/symfony v3.0.2 replaces symfony/yaml (self.version)

$ composer depends symfony/yaml -t
symfony/symfony v3.0.2 The Symfony PHP framework
|- phpunit/phpunit 5.2.4 (requires symfony/yaml ~2.1|~3.0)
|  `- __root__ (requires (for development) phpunit/phpunit ^5.2)
`- symfony/symfony v3.0.2 (replaces symfony/yaml self.version)
   `- __root__ (requires symfony/symfony ^3.0)
```

### CODE REVIEW

File: src/Composer/Command/DependsCommand.php [hunk 1]
```diff
@@ -61,80 +63,153 @@ protected function configure()
...
-                    return $link->getTarget();
-                }, $package->getReplaces()));
+    /**
+     * @param string $needle The package to inspect.
+     * @param ConstraintInterface|null $constraint Optional constraint to filter by.
+     * @param bool $invert Whether to invert matches on the previous constraint.
+     * @param bool $recurse Whether to recursively expand the requirement tree.
+     * @return array An array with dependers as key, and as values an array containing the source package and the link respectively
+     */
+    private function getDependers($needle, $constraint = null, $invert = false, $recurse = true)
```
Comment (Seldaek) [inline src/Composer/Command/DependsCommand.php]: getDependents?

File: src/Composer/Command/DependsCommand.php [hunk 2]
```diff
@@ -32,22 +35,21 @@
  */
 class DependsCommand extends Command
 {
-    protected $linkTypes = array(
-        'require' => array('requires', 'requires'),
-        'require-dev' => array('devRequires', 'requires (dev)'),
-    );
+    /** @var CompositeRepository  */
+    private $repository;
```
Comment (Seldaek) [inline src/Composer/Command/DependsCommand.php]: Not a fan of adding state like this, as it makes all methods depend on the instance while they could mostly be static methods, all you need is to pass $repo to getDependers AFAICT. It makes it easier to extract code into an external class (which would be good to make some of this testable eventually) when you have less object state to care about.

Comment (curry684) [inline src/Composer/Command/DependsCommand.php]: Agreed, it's kind of a weak solution to that it's currently not really better feasible. From a purist perspective it's currently correct, it's a property of the command, but that's only correct as the logic itself is as well. True issue is (but we all know that) that there should be a big cleanup session one day to remove all logic from the commands and only have a few oneliner calls and rendering.

File: doc/03-cli.md [hunk 3]
```diff
@@ -350,12 +350,11 @@ php composer.phar depends symfony/symfony --with-replaces -im ^3.0
```
Comment (Seldaek) [inline doc/03-cli.md]: Could you also update the use case above with symfony lala? Because it uses stuff you removed, if you could update it to do the equivalent using the new flags that'd be good, because this was a good advanced use case IMO.

Comment (curry684) [inline doc/03-cli.md]: Oops didn't scroll back far enough hehe. Coming up.

Comment (curry684) [inline doc/03-cli.md]: Had to change the samples a bit as they were no longer reproducable, but think it's fine now.

Comment (Seldaek) [inline doc/03-cli.md]: No longer repro because you removed the --with-replaces? I'm just trying to understand the change as the PR is pretty hard to review. --with-replaces was pretty nice to see anything that blocks symfony/symfony from being upgraded due to a require on symfony/symfony *or* anything it replaces.

File: src/Composer/Command/DependsCommand.php [hunk 4]
```diff
@@ -61,80 +60,153 @@ protected function configure()
...
+        $results = array();
+
+        /**
+         * Loop over all currently installed packages.
+         */
+        foreach ($packages as $package) {
+            // Retrieve all requirements, but dev only for the root package
+            $links = $package->getRequires();
+            $links += $package->getReplaces();
+            if ($package instanceof RootPackage) {
```
Comment (stof) [inline src/Composer/Command/DependsCommand.php]: you should use the interface actually

File: src/Composer/Command/DependsCommand.php [hunk 5]
```diff
@@ -61,80 +60,153 @@ protected function configure()
...
+        $needles = is_array($needle) ? $needle : array($needle);
+        $results = array();
+
+        /**
+         * Loop over all currently installed packages.
+         */
+        foreach ($packages as $package) {
+            // Retrieve all requirements, but dev only for the root package
+            $links = $package->getRequires();
+            $links += $package->getReplaces();
```
Comment (stof) [inline src/Composer/Command/DependsCommand.php]: Why are you merging replacements and requirements ? These are totally different so it looks weird to treat them the same way

File: src/Composer/Command/DependsCommand.php [hunk 6]
```diff
@@ -61,80 +60,153 @@ protected function configure()
...
+     * @param string $needle The package to inspect.
+     * @param PackageInterface[] $packages List of installed packages.
+     * @param ConstraintInterface|null $constraint Optional constraint to filter by.
+     * @param bool $invert Whether to invert matches on the previous constraint.
+     * @param bool $recurse Whether to recursively expand the requirement tree.
+     * @return array An array with dependers as key, and as values an array containing the source package and the link respectively
+     */
+    private function getDependents($needle, $packages, $constraint = null, $invert = false, $recurse = true)
+    {
+        $needles = is_array($needle) ? $needle : array($needle);
```
Comment (stof) [inline src/Composer/Command/DependsCommand.php]: this can never be an array according to the phpdoc, so something is wrong

File: src/Composer/Command/DependsCommand.php [hunk 7]
```diff
@@ -61,80 +60,153 @@ protected function configure()
...
+            $constraint = null;
+        }
+        $matchInvert = $input->getOption('invert-match-constraint');
+        $renderTree = $input->getOption('tree');
+        $recursive = $renderTree || $input->getOption('recursive');
+
+        // Resolve dependencies
+        $results = $this->getDependents($needle, $repository->getPackages(), $constraint, $matchInvert, $recursive);
+        if (empty($results)) {
+            $extra = isset($constraint) ? sprintf(' in versions %smatching %s', $matchInvert ? 'not ' : '', $textConstraint) : '';
```
Comment (stof) [inline src/Composer/Command/DependsCommand.php]: please use ``null !== $constraint`` to check for ``null`` instead of ``isset``. We don't want to allow undefined variables here

File: src/Composer/Command/DependsCommand.php [hunk 8]
```diff
@@ -61,80 +60,153 @@ protected function configure()
...
+            $versionText = (strpos($package->getPrettyVersion(), 'No version set') === 0) ? '' : $package->getPrettyVersion();
+            $packageText = rtrim(sprintf('%s %s', $package->getPrettyName(), $versionText));
+            $linkText = implode(' ', array($link->getDescription(), $link->getTarget(), $link->getPrettyConstraint()));
+            $output->write(sprintf("%s%s %s (%s)\n", $prefix, $isLast ? '`-' : '|-', $packageText, $linkText));
+            $this->printTree($output, $children, $prefix . ($isLast ? '   ' : '|  '));
+        }
+    }
 
-        $needles = array($needle);
-        if (true === $input->getOption('with-replaces')) {
```
Comment (stof) [inline src/Composer/Command/DependsCommand.php]: This logic adding packages replacing the needle in the list of needles too should be preserved to keep the existing features (and I suggest keeping the option)

Comment (stof) [inline src/Composer/Command/DependsCommand.php]: note that this array of needles is what you should pass to ``getDependants`` in your new system.

**Comment by curry684** [comment]
I realize now what was bugging me about the `--with-replaces` option: the scenarios I tried only gave nonsensical results, but that was because it was overeager.

Say I have 2 packages `foo/bar` and `bar/foo` depending on `symfony/console' and `symfony/yaml` respectively, but I have installed `symfony/symfony` which replaces both. The old implementation would show the second dependency as well when querying the first, which is just plain wrong - it's an entirely different branch of the project's dependency true.

**However**, with the example in the docs:

    php composer.phar depends symfony/symfony --with-replaces -im ^3.0

Now it suddenly does make sense to expand into the replaced packages (so downwards, not up) as a dependency on `symfony/console:2.7` may very well be blocking installation of `symfony/symfony:3.0`.

I'll have to think a bit about whether that warrants having the option back, as I think it's well possible to implement default behaviour which fits all cases. I'll get to fixing that later on - most of the remarks here are related to the leftovers of this, like the array parameter :thumbsup:

File: src/Composer/Command/DependsCommand.php (hunk 5 above)
Comment (curry684) [inline src/Composer/Command/DependsCommand.php]: From the dependency standpoint they're the same. It's an upward link causing a package to be present: whether `symfony/console` is installed because `symfony/symfony` replaces it, or because it requires it, is functionally moot - in both cases `symfony/symfony` is the reason that `symfony/console` is installed. So yes, they are equivalently merged, with differentiation in the output.

File: doc/03-cli.md (hunk 3 above)
Comment (curry684) [inline doc/03-cli.md]: Only the second example. I had to replace the `monolog/monolog` sample because most packages have it in `require-dev`, so the old docs were actually a good example of that part not correctly functioning.

I can get into that it's hard to review, it's a complex bit of nastiness with nasty exceptions. I'm actually just realizing that the `-im --with-replaces` functionality was broken too to detect blockers as it ignores `conflicts`.

**Comment by curry684** [comment]
Ok, had a lot more thinking time on this, and I came to the conclusion the underlying issue is that the previous implementation of this command was invalidly trying to combine 2 completely different things. Looking at `aptitude`, they have separated this behavior in 2 commands: `why` and `why-not`. The first checks for problems preventing **removal** of a package, the second checks for problems preventing **installation** of a package.

The current implementation of `depends` tries to haphazardly combine them. But on its own the `-m` flag is pretty much pointless - `c depends symfony/symfony -m 3.5` tells me nothing that isn't plain obvious from `c depends symfony/symfony`.

The `-i` flag is documented everywhere to invert the behavior of `-m`, but actually is valid standalone and useful, as `-m` defaults to `*` - it will just show why no version whatsoever of that package will ever be installed, for example because of conflicts. Combined with `-m` it can be ultra powerful. But only, and that's the real catch, if it also implies the old behavior of `--with-replaces`. Which is useless **without** `-i` as it resolves the wrong way then.

So yes, I think the `--with-replaces` behavior should go back in, but not as its own option, but implicit when `-i` is also specified.

The syntax and use for this powerful command would probably have been a lot clearer and cleaner if it had been split to begin with:
```
composer [depends|why] <package> (<constraint>)
composer [prohibits|why-not] <package> (<constraint>)
```

**Comment by Seldaek** [comment]
I don't mind breaking BC on such small args, especially since they're pretty new (AFAIK not even in a tagged release). Let's do it clean, having two commands sounds good, and will force us to move most of this code away from Command classes :)

**Comment by curry684** [comment]
Ok, I'll get on that then :smile:

**Comment by curry684** [comment]
Well @Seldaek good luck, did my best to make it harder to review  :wink:

File: src/Composer/Command/DependsCommand.php [hunk 9]
```diff
@@ -59,82 +41,15 @@ protected function configure()
...
-            sort($messages);
-            $io->write($messages);
-        } else {
-            $matchText = '';
-            if ($input->getOption('match-constraint') !== '*') {
-                $matchText = ' in versions '.($matchInvert ? 'not ' : '').'matching ' . $input->getOption('match-constraint');
-            }
-            $io->writeError('<info>There is no installed package depending on "'.$needle.'"'.$matchText.'.</info>');
-        }
+        parent::doExecute($input, $output, false);
```
Comment (staabm) [inline src/Composer/Command/DependsCommand.php]: Either phpdoc is wrong or this line should return

File: src/Composer/Command/ProhibitsCommand.php [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+    /**
+     * Execute the function.
+     *
+     * @param InputInterface $input
+     * @param OutputInterface $output
+     * @return int|null
+     */
+    protected function execute(InputInterface $input, OutputInterface $output)
+    {
+        parent::doExecute($input, $output, true);
```
Comment (staabm) [inline src/Composer/Command/ProhibitsCommand.php]: Same here: misses return?

File: src/Composer/Repository/BaseRepository.php [hunk 11]
```diff
@@ -0,0 +1,70 @@
...
+     *
+     * @param string|string[] $needle The package name(s) to inspect.
+     * @param ConstraintInterface|null $constraint Optional constraint to filter by.
+     * @param bool $invert Whether to invert matches to discover reasons for the package *NOT* to be installed.
+     * @param bool $recurse Whether to recursively expand the requirement tree up to the root package.
+     * @return array An associative array of arrays as described above.
+     */
+    public function getDependents($needle, $constraint = null, $invert = false, $recurse = true)
+    {
+        $needles = is_array($needle) ? $needle : array($needle);
```
Comment (staabm) [inline src/Composer/Repository/BaseRepository.php]: Could be simplified to `$needles = (array) $needle;`

File: src/Composer/Command/BaseDependencyCommand.php [hunk 12]
```diff
@@ -0,0 +1,188 @@
...
+            new InputOption(self::OPTION_TREE, 't', InputOption::VALUE_NONE, 'Prints the results as a nested tree'),
+        ));
+    }
+
+    /**
+     * Execute the command.
+     *
+     * @param InputInterface $input
+     * @param OutputInterface $output
+     * @param bool @inverted Whether
```
Comment (staabm) [inline src/Composer/Command/BaseDependencyCommand.php]: Doc incomplete

File: src/Composer/Command/DependsCommand.php (hunk 9 above)
Comment (curry684) [inline src/Composer/Command/DependsCommand.php]: The ancestor implementation defines the return value, so IDE complains about invalid phpdoc if it isn't inherited, but returning null is implicit, and as that is allowed by the phpdoc this construct is valid. The other commands were already doing the same actually.

File: src/Composer/Repository/BaseRepository.php (hunk 11 above)
Comment (curry684) [inline src/Composer/Repository/BaseRepository.php]: Funny, had to look it up but that is indeed defined behaviour now, thought it was still semi undefined as automatic conversion still is :+1:

File: src/Composer/Console/Application.php [hunk 13]
```diff
@@ -279,33 +279,35 @@ public function getHelp()
...
+            new Command\StatusCommand(),
+            new Command\ArchiveCommand(),
+            new Command\DiagnoseCommand(),
+            new Command\RunScriptCommand(),
+            new Command\LicensesCommand(),
+            new Command\GlobalCommand(),
+            new Command\ClearCacheCommand(),
+            new Command\RemoveCommand(),
+            new Command\HomeCommand(),
+        ));
```
Comment (Seldaek) [inline src/Composer/Console/Application.php]: Not sure what this change is good for? Also completely not related to the PR, which makes reviewing even harder.

File: src/Composer/Command/BaseCommand.php [hunk 14]
```diff
@@ -26,7 +26,7 @@
  * @author Ryan Weaver <ryan@knplabs.com>
  * @author Konstantin Kudryashov <ever.zet@gmail.com>
  */
-abstract class Command extends BaseCommand
+abstract class BaseCommand extends Command
```
Comment (Seldaek) [inline src/Composer/Command/BaseCommand.php]: Also don't see the point of renaming this. Lots of changes for nothing, and especially not relevant to the PR.

Comment (curry684) [inline src/Composer/Command/BaseCommand.php]: I needed a common ancestor for Depends and Prohibits. Could've just called it `DependencyCommand`, but that would've started obfuscation hell imo as there would be no visible distinction in the `Composer/Command` namespace between implementations and base classes. So as other namespace were already following the `BaseX` convention, like `BasePackage`, and we agreed here to start cleaning up the commands anyway, I refactored it into consistency, and now the Command namespace has a clear distinction between Base classes, both `abstract`, and other classes.

File: src/Composer/Console/Application.php (hunk 13 above)
Comment (curry684) [inline src/Composer/Console/Application.php]: Unrelated, true, just something I hit while adding the `ProhibitsCommand`. Would appear this once started as 3 single array inserts and the next 20 commands were just copy/pasted without considering for that many a single bulk merge makes more sense than 23 single inserts.

Will happily revert it if you disagree  :)

**Comment by Seldaek** [comment]
Thanks! Merged and did a couple minor fixes in d7855d03c7fd9a7afdc5f8d9c68cd74e8611cc60. If you do get a chance though once thing that'd be nice is to merge the ShowCommand tree display with this tree display so they get the same coloring treatment, because right now this one is kinda hard to read w/o color compared to the show -t one :)

Just one thing that trips me up, if you use `prohibits` without specifying a version number it basically acts like `depends`, right? I think it should error out because just listing what requires the package really doesn't tell you why the package can't be installed. If it's a meaningless use case I think we should at the very least warn.

**Comment by curry684** [comment]
1. I'm considering submitting a decent tree renderer to symfony/console as it already has the table helper. That would allow us to replace both, as indeed they are different now here. I would probably dev it here to standardize behavior of both then submit a PR there. I looked into reusing the Show renderer but it's messily integrated and hard to extract right now.
2. Prohibits right now should require a version indeed. Thing is, without version it should do a full solution, and right now it naively acts on installed packages like before the -i option was pretty useless without -m. So it's not worse than before but has definite room for improvement. It's something we should discuss in a separate issue or elsewhere first as it has pretty complex consequences.

**Comment by curry684** [comment]
Your fixes are :+1: btw
