### PR TITLE
Fix handling of upper-bound platform req ignores to not act on conflicts

### LINKED ISSUE #11020: Extraneous conflict when using `--ignore-platform-req=php+`
My `composer.json`:

```json
{
    "name": "example/ignoretest",
    "require": {
        "php-amqplib/php-amqplib": "3.2.0"
    }
}
```

Output of `composer diagnose`:

```
...
Composer version: 2.5-dev+b6028951b8a2254d4896b4dd13bcbe380a3d51bf
PHP version: 8.1.2
...
```

When I run this command:

```
composer update --ignore-platform-req=php+
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php is present at version 8.1.2 and cannot be modified by Composer
    - php-amqplib/php-amqplib v3.2.0 conflicts with php 7.4.0 - 7.4.1.
    - Root composer.json requires php-amqplib/php-amqplib 3.2.0 -> satisfiable by php-amqplib/php-amqplib[v3.2.0].
```

It runs fine without the `ignore-platform-req` parameter. Maybe Composer ignores the upper bound of the `conflicts` declaration as well?

### PR DESCRIPTION
**Pull request by Seldaek**
fixes #11020

### CODE REVIEW

File: src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php [hunk 1]
```diff
@@ -60,13 +60,16 @@ public function isIgnored(string $req): bool
...
+     * @param bool $allowUpperBoundOverride For conflicts we do not want the upper bound to be skipped
+     */
+    public function filterConstraint(string $req, ConstraintInterface $constraint, bool $allowUpperBoundOverride = true): ConstraintInterface
     {
         if (!PlatformRepository::isPlatformPackage($req)) {
             return $constraint;
         }
 
-        if (!Preg::isMatch($this->ignoreUpperBoundRegex, $req)) {
+        if (!Preg::isMatch($this->ignoreUpperBoundRegex, $req) || !$allowUpperBoundOverride) {
```
Comment (stof) [inline src/Composer/Filter/PlatformRequirementFilter/IgnoreListPlatformRequirementFilter.php:72]: I would swap the OR conditions as checking the boolean variable will be faster than running a regexp

**Review by stof — APPROVED** [review]

**Review by naderman — APPROVED** [review]
