### PR TITLE
Fix inline aliases not being loaded when extracting dev requirements

### LINKED ISSUE #8954: Inline Alias not working in 2.0.0-alpha1
My `composer.json`:

```json
...
        "cakephp/authentication": "^2.0",
        "cakephp/authorization": "^2.0",
        "cakephp/cakephp": "dev-4.next as 4.1.0-RC2",
...
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.0-alpha1
PHP version: 7.4.4 - Package overridden via config.platform, actual: 7.4.7-dev
PHP binary path: c:\program files\php\php.exe
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer update
```

I get the following output:

```
  Problem 1
    - Root composer.json requires cakephp/authentication ^2.0 -> satisfiable by cakephp/authentication[2.3.0].
    - cakephp/authentication 2.3.0 requires cakephp/core ^4.0 -> could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Root composer.json requires cakephp/authorization ^2.0 -> satisfiable by cakephp/authorization[2.0.3].
    - cakephp/authorization 2.0.3 requires cakephp/cakephp ^4.0 -> found cakephp/cakephp[dev-4.next] but it does not match the constraint.
...
```

And I expected this to happen:
In Composer 1.10.7 running `composer update` works fine and installs dev-4.next branch without issues.

### PR DESCRIPTION
**Pull request by Seldaek**
Fixes #8954

### CODE REVIEW

File: src/Composer/Repository/RepositorySet.php [hunk 1]
```diff
@@ -270,4 +285,18 @@ public function createPoolForPackages($packageNames, LockArrayRepository $locked
 
         return $this->createPool($request, new NullIO());
     }
+
+    private function getRootAliasesPerPackage(array $aliases)
```
Comment (GrahamCampbell) [inline src/Composer/Repository/RepositorySet.php:289]: can be static
