### PR TITLE
Fix broken junctions leads to installation failure

### LINKED ISSUE #11549: mkdir(): No such file or directory
My `composer.json`:

```json
{
  "name": "attia/install-bug",
  "autoload": {
    "psr-4": {
      "Attia\\InstallBug\\": "src/"
    }
  },
  "require": {
    "attia/package": "dev-main"
  },
  "repositories": [
    {
      "type": "path",
      "url": "./packages/package"
    }
  ],
  "minimum-stability": "dev"
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK git version 2.41.0
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.8
PHP version: 8.1.10
PHP binary path: E:\laragon\bin\php\php-8.1.10-Win32-vs16-x64\php.exe
OpenSSL version: OpenSSL 1.1.1q  5 Jul 2022
cURL version: 7.77.0 libz 1.2.12 ssl OpenSSL/1.1.1q
zip: extension present, unzip not available, 7-Zip not available
```

When I run this command: 

```
composer install -vvv
```

I get the following output: 

```
Running 2.5.8 (2023-06-09 17:13:21) with PHP 8.1.10 on Windows NT / 10.0
Reading ./composer.json (E:\projects\install-bug\composer.json)
Loading config file C:/Users/holyd/AppData/Roaming/Composer/auth.json
Loading config file ./composer.json (E:\projects\install-bug\composer.json)
Checked CA file /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/certs/ca-certificates.crt does not exist or it is not a file.
Checked directory /etc/ssl/certs/ca-certificates.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/ca-bundle.pem does not exist or it is not a file.
Checked directory /etc/ssl/ca-bundle.pem does not exist or it is not a directory.
Checked CA file /usr/local/share/certs/ca-root-nss.crt does not exist or it is not a file.
Checked directory /usr/local/share/certs/ca-root-nss.crt does not exist or it is not a directory.
Checked CA file /usr/ssl/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/ssl/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /opt/local/share/curl/curl-ca-bundle.crt does not exist or it is not a file.
Checked directory /opt/local/share/curl/curl-ca-bundle.crt does not exist or it is not a directory.
Checked CA file /usr/local/share/curl/curl-ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/local/share/curl/curl-ca-bundle.crt does not exist or it is not a directory.
Checked CA file /usr/share/ssl/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/share/ssl/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/cert.pem does not exist or it is not a file.
Checked directory /etc/ssl/cert.pem does not exist or it is not a directory.
Checked CA file /usr/local/etc/ssl/cert.pem does not exist or it is not a file.
Checked directory /usr/local/etc/ssl/cert.pem does not exist or it is not a directory.
Checked CA file /usr/local/etc/openssl/cert.pem does not exist or it is not a file.
Checked directory /usr/local/etc/openssl/cert.pem does not exist or it is not a directory.
Checked CA file /usr/local/etc/openssl@1.1/cert.pem does not exist or it is not a file.
Checked directory /usr/local/etc/openssl@1.1/cert.pem does not exist or it is not a directory.
Checked CA file /etc/pki/tls/certs does not exist or it is not a file.
Checked directory /etc/pki/tls/certs does not exist or it is not a directory.
Checked CA file /etc/ssl/certs does not exist or it is not a file.
Checked directory /etc/ssl/certs does not exist or it is not a directory.
Checked CA file /etc/ssl does not exist or it is not a file.
Checked directory /etc/ssl does not exist or it is not a directory.
Checked CA file /usr/local/share/certs does not exist or it is not a file.
Checked directory /usr/local/share/certs does not exist or it is not a directory.
Checked CA file /usr/ssl/certs does not exist or it is not a file.
Checked directory /usr/ssl/certs does not exist or it is not a directory.
Checked CA file /opt/local/share/curl does not exist or it is not a file.
Checked directory /opt/local/share/curl does not exist or it is not a directory.
Checked CA file /usr/local/share/curl does not exist or it is not a file.
Checked directory /usr/local/share/curl does not exist or it is not a directory.
Checked CA file /usr/share/ssl/certs does not exist or it is not a file.
Checked directory /usr/share/ssl/certs does not exist or it is not a directory.
Checked CA file /etc/ssl does not exist or it is not a file.
Checked directory /etc/ssl does not exist or it is not a directory.
Checked CA file /usr/local/etc/ssl does not exist or it is not a file.
Checked directory /usr/local/etc/ssl does not exist or it is not a directory.
Checked CA file /usr/local/etc/openssl does not exist or it is not a file.
Checked directory /usr/local/etc/openssl does not exist or it is not a directory.
Checked CA file /usr/local/etc/openssl@1.1 does not exist or it is not a file.
Checked directory /usr/local/etc/openssl@1.1 does not exist or it is not a directory.
Checked CA file C:\Users\holyd\AppData\Local\Temp\opeAE23.tmp: valid
Executing command (E:\projects\install-bug): git branch -a --no-color --no-abbrev -v
Executing command (E:\projects\install-bug): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (E:\projects\install-bug): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (E:\projects\install-bug): hg branch
Executing command (E:\projects\install-bug): fossil branch list
Executing command (E:\projects\install-bug): fossil tag list
Executing command (E:\projects\install-bug): svn info --xml
Reading C:/Users/holyd/AppData/Roaming/Composer/composer.json (C:\Users\holyd\AppData\Roaming\Composer\composer.json)
Loading config file C:/Users/holyd/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/holyd/AppData/Roaming/Composer/composer.json (C:\Users\holyd\AppData\Roaming\Composer\composer.json)
Loading config file C:\Users\holyd\AppData\Roaming\Composer/auth.json
Reading C:\Users\holyd\AppData\Roaming\Composer/auth.json (C:\Users\holyd\AppData\Roaming\Composer\auth.json)
Reading ./composer.lock (E:\projects\install-bug\composer.lock)
Reading E:\projects\install-bug/vendor/composer/installed.json (E:\projects\install-bug\vendor\composer\installed.json)
Reading C:/Users/holyd/AppData/Roaming/Composer/vendor/composer/installed.json (C:\Users\holyd\AppData\Roaming\Composer\vendor\composer\installed.json)
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Reading ./composer.lock (E:\projects\install-bug\composer.lock)
Built pool.
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Package operations: 1 install, 0 updates, 0 removals
Installs: attia/package:dev-main
  - Installing attia/package (dev-main): Junctioning from ./packages/packageExecuting command (CWD): mklink /J E:\projects\install-bug\vendor\attia\package E:\projects\install-bug\packages\package

    Symlink failed, fallback to use mirroring!
    Mirroring from ./packages/package    Install of attia/package failed

In Filesystem.php line 97:

  [Symfony\Component\Filesystem\Exception\IOException]
  Failed to create "E:\projects\install-bug\vendor/attia/package": mkdir(): No such file or directory


Exception trace:
  at phar://C:/composer/composer.phar/vendor/symfony/filesystem/Filesystem.php:97
 Symfony\Component\Filesystem\Filesystem->mkdir() at phar://C:/composer/composer.phar/vendor/symfony/filesystem/Filesystem.php:570
 Symfony\Component\Filesystem\Filesystem->mirror() at phar://C:/composer/composer.phar/src/Composer/Downloader/PathDownloader.php:151
 Composer\Downloader\PathDownloader->install() at phar://C:/composer/composer.phar/src/Composer/Downloader/DownloadManager.php:270
 Composer\Downloader\DownloadManager->install() at phar://C:/composer/composer.phar/src/Composer/Installer/LibraryInstaller.php:280
 Composer\Installer\LibraryInstaller->installCode() at phar://C:/composer/composer.phar/src/Composer/Installer/LibraryInstaller.php:152
 Composer\Installer\LibraryInstaller->install() at phar://C:/composer/composer.phar/src/Composer/Installer/InstallationManager.php:463
 Composer\Installer\InstallationManager->install() at phar://C:/composer/composer.phar/src/Composer/Installer/InstallationManager.php:378
 Composer\Installer\InstallationManager->Composer\Installer\{closure}() at phar://C:/composer/composer.phar/vendor/react/promise/src/FulfilledPromise.php:28
 React\Promise\FulfilledPromise->then() at phar://C:/composer/composer.phar/src/Composer/Installer/InstallationManager.php:379
 Composer\Installer\InstallationManager->executeBatch() at phar://C:/composer/composer.phar/src/Composer/Installer/InstallationManager.php:319
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar://C:/composer/composer.phar/src/Composer/Installer/InstallationManager.php:218
 Composer\Installer\InstallationManager->execute() at phar://C:/composer/composer.phar/src/Composer/Installer.php:797
 Composer\Installer->doInstall() at phar://C:/composer/composer.phar/src/Composer/Installer.php:289
 Composer\Installer->run() at phar://C:/composer/composer.phar/src/Composer/Command/InstallCommand.php:146
 Composer\Command\InstallCommand->execute() at phar://C:/composer/composer.phar/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar://C:/composer/composer.phar/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/composer/composer.phar/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar://C:/composer/composer.phar/src/Composer/Console/Application.php:378
 Composer\Console\Application->doRun() at phar://C:/composer/composer.phar/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar://C:/composer/composer.phar/src/Composer/Console/Application.php:141
 Composer\Console\Application->run() at phar://C:/composer/composer.phar/bin/composer:88
 require() at C:\composer\composer.phar:29

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--download-only] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [--audit] [--audit-format AUDIT-FORMAT] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]

```

And I expected this to happen:
installing normally

### PR DESCRIPTION
**Pull request by Attia-Ahmed**
Fixes #11549
Root Cause: When changing the project folder, existing junctions in Windows **(created using absolute paths)** become invalid. The "mklink /J" command used to create junctions results in an error ("Cannot create a file when that file already exists.") if a previous junction with a different target exists, as the junction is stored as an absolute path. This error causes package folders to have junctions with the wrong target directory, leading to [mkdir(): No such file or directory](https://github.com/composer/composer/issues/11549)

Windows Behavior: Windows prohibits creating a new junction if a file or junction with the same name already exists.

Solution: The bug fix ensures a clean execution by removing any previous junctions before creating new ones, regardless of whether they are broken or non-broken junctions. This resolves the installation failure caused by junctioning the package folder with the correct target directory.

Importance: This bug fix is crucial for Windows development environments. Developers may unknowingly encounter this issue when changing folder names or moving projects.

### CODE REVIEW

File: src/Composer/Util/Filesystem.php [hunk 1]
```diff
@@ -814,6 +814,12 @@ public function junction($target, $junction)
         if (!is_dir($target)) {
             throw new IOException(sprintf('Cannot junction to "%s" as it is not a directory.', $target), 0, null, $target);
         }
+
+        // Removing any previously junction to ensure clean execution.
+        if (!is_dir($junction) or $this->isJunction($junction)) {
```
Comment (stof) [inline src/Composer/Util/Filesystem.php:819]: this should use the boolean operator `||` rather than `or` which has a totally different precedence.

Comment (Attia-Ahmed) [reply src/Composer/Util/Filesystem.php]: I don't think it matters in this use case, but I did the refactor for code consitancy👍, thanks!

**Comment by Seldaek** [comment]
Thanks, merged in 2.2 and 2.6 (ce876e7a6)

File: src/Composer/Util/Filesystem.php [hunk 2]
```diff
@@ -814,6 +814,12 @@ public function junction($target, $junction)
         if (!is_dir($target)) {
             throw new IOException(sprintf('Cannot junction to "%s" as it is not a directory.', $target), 0, null, $target);
         }
+
+        // Removing any previously junction to ensure clean execution.
+        if (!is_dir($junction) || $this->isJunction($junction)) {
+            @rmdir($junction);
```
[the remark this answers is not in the document]
Comment (Attia-Ahmed) [reply src/Composer/Util/Filesystem.php:820]: Thank you for your observation on the use of `rmdir()`. In this specific scenario, we're dealing with Windows junctions, which can sometimes be corrupted or broken. Standard PHP functions like `is_dir()`, `is_file()`, and `is_link()` have proven unreliable for detecting the existence such corrupted junctions. However, `rmdir()` has been effective in removing both valid and broken junctions, which is why it's used here, even when `is_dir()` returns `false`.

It's important to note that the original `removeJunction` function in the same class also relies on `rmdir()`. However, it throws an exception if `is_dir()` fails, making it unsuitable for this particular case.

If you'd like to explore alternative solutions, I'd invite you to run the `testOverrideJunctions` test, which will fail if we change this behavior. Feel free to give it a try and suggest a more convenient approach that ensures the test works as expected.
